/// Singleton SQLite database manager for MS Unit Converter.
///
/// Responsibilities:
/// - Open the SQLite database (creating schema on first launch via [MigrationService]).
/// - Check [_contentVersion] against the stored version; reseed from Dart data
///   if the content has changed (new app release with updated data).
/// - Expose a single [Database] instance to all repositories via [database].
///
/// ## Phase 1 Architecture
/// The database is seeded **at runtime** from existing Dart data structures
/// on first launch. This avoids any build-tool or binary-asset dependency.
///
/// ## Phase 2 Architecture (future)
/// The database will be shipped as a pre-built binary asset
/// (`assets/database/unit_converter.db`) generated by `tools/build_database.dart`
/// from JSON content files. `DatabaseService` will copy the asset to the
/// documents directory and open it from there instead of seeding at runtime.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

import '../core/constants.dart';
import 'migration_service.dart';
import '../data/collections_data.dart';
import '../data/converter_config.dart';
import '../data/currencies_data.dart';
import '../data/did_you_know.dart';
import '../data/units_data.dart';

/// Current content version — matches the app release that last changed reference data.
/// Increment this when any reference data changes (units, currencies, facts, etc.)
/// to trigger an automatic reseed on the next launch.
const String _contentVersion = '2.3.2';

/// SQLite database filename stored in the app documents directory.
const String _dbFileName = DatabaseConstants.databaseFileName;

/// Sole owner of SQLite database lifecycle.
///
/// ## ARCHITECTURE GUARDRAILS
/// Responsibilities:
/// - Copy pre-populated asset database on first launch
/// - Open and manage database connection
/// - Run schema migrations via [MigrationService]
/// - Handle content version management
///
/// **STRICT RULE**: Never implement unit conversions, business logic, or UI state here.
class DatabaseService {
  DatabaseService._();

  /// The singleton instance.
  static final DatabaseService instance = DatabaseService._();

  Database? _db;
  bool _initialized = false;

  /// Returns whether the database has been initialized and is open.
  bool get isInitialized => _initialized && _db != null && _db!.isOpen;

  /// Returns the open [Database] instance.
  ///
  /// Throws a [StateError] if [initialize] has not been called first.
  Database get database {
    if (!isInitialized) {
      throw StateError(
        'DatabaseService not initialized. '
        'Call DatabaseService.instance.initialize() before accessing the database.',
      );
    }
    return _db!;
  }

  /// Initializes the database: opens it, runs migrations, and seeds data if needed.
  ///
  /// Safe to call multiple times — subsequent calls are no-ops.
  /// First checks if the pre-populated asset database exists and copies it to
  /// the app documents directory if no database exists yet.
  Future<void> initialize() async {
    if (_initialized && _db != null && _db!.isOpen) return;

    if (!kIsWeb && (Platform.isLinux || Platform.isWindows || Platform.isMacOS)) {
      sqfliteFfiInit();
      databaseFactory = databaseFactoryFfi;
    }

    final stopwatch = Stopwatch()..start();

    try {
      final dbPath = await _resolveDbPath();
      final dbFile = File(dbPath);

      if (!await dbFile.exists()) {
        await _copyPrePopulatedDatabase(dbPath);
      }

      debugPrint('[DatabaseService] Opening database at: $dbPath');

      _db = await openDatabase(
        dbPath,
        version: MigrationService.currentSchemaVersion,
        onCreate: (db, version) async {
          debugPrint('[DatabaseService] Creating schema (version $version)');
          await MigrationService.createSchema(db);
          await _clearReferenceData(db);
          await _seedAllData(db);
          await _writeVersions(db);
        },
        onUpgrade: (db, oldVersion, newVersion) async {
          debugPrint(
            '[DatabaseService] Upgrading schema: $oldVersion → $newVersion',
          );
          await MigrationService.upgrade(db, oldVersion, newVersion);
          // After a schema upgrade, check if content also needs refreshing.
          await _reseedIfContentChanged(db);
        },
        onOpen: (db) async {
          debugPrint('[DatabaseService] Database opened — checking content version');
          await _reseedIfContentChanged(db);
        },
      );

      _initialized = true;
      stopwatch.stop();

      if (kDebugMode) {
        final sizeKb = await dbFile.exists()
            ? (await dbFile.length() / 1024).toStringAsFixed(2)
            : '0.00';
        debugPrint(
          '[DatabaseService] Initialized in ${stopwatch.elapsedMilliseconds}ms — File size: $sizeKb KB',
        );
      }
    } catch (e, st) {
      stopwatch.stop();
      debugPrint('[DatabaseService] Initialization error: $e\n$st');
      rethrow;
    }
  }

  /// Copies the pre-populated SQLite asset database from [rootBundle] to [targetPath].
  ///
  /// Returns `true` if successfully copied, `false` otherwise (e.g. asset missing in tests).
  Future<bool> _copyPrePopulatedDatabase(String targetPath) async {
    try {
      debugPrint('[DatabaseService] Copying pre-populated asset database to: $targetPath');
      final file = File(targetPath);
      await file.parent.create(recursive: true);

      final data = await rootBundle.load(DatabaseConstants.databaseAssetPath);
      final bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await file.writeAsBytes(bytes, flush: true);
      debugPrint('[DatabaseService] Pre-populated database asset copied (${bytes.length} bytes)');
      return true;
    } catch (e) {
      debugPrint(
        '[DatabaseService] Asset database copy omitted/failed (falling back to dynamic seed): $e',
      );
      return false;
    }
  }

  /// Seeds all reference data and writes version metadata into [db].
  ///
  /// Exposed for [tools/build_database.dart] to generate pre-populated binaries.
  static Future<void> seedDatabase(Database db) async {
    await MigrationService.createSchema(db);
    await instance._clearReferenceData(db);
    await instance._seedAllData(db);
    await instance._writeVersions(db);
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  /// Resolves the absolute file path for storing the SQLite database file.
  Future<String> _resolveDbPath() async {
    try {
      final docsDir = await getApplicationDocumentsDirectory();
      return path.join(docsDir.path, _dbFileName);
    } catch (_) {
      // Fallback for headless unit test runner where path_provider plugin is unmocked
      return path.join(Directory.systemTemp.path, _dbFileName);
    }
  }

  /// Checks if the content version in the DB matches [_contentVersion].
  /// Reseeds reference data if the version has changed.
  Future<void> _reseedIfContentChanged(Database db) async {
    final storedVersion = await _readContentVersion(db);
    if (storedVersion == _contentVersion) {
      debugPrint('[DatabaseService] Content version current ($_contentVersion) — skip reseed');
      return;
    }

    debugPrint(
      '[DatabaseService] Content version changed: ${storedVersion ?? 'none'} → $_contentVersion — reseeding reference tables…',
    );
    await _clearReferenceData(db);
    await _seedAllData(db);
    await _writeVersions(db);
  }

  /// Reads the stored content version from the [content_version] table.
  Future<String?> _readContentVersion(Database db) async {
    try {
      final rows = await db.query('content_version', limit: 1);
      if (rows.isEmpty) return null;
      return rows.first['version'] as String?;
    } catch (_) {
      return null;
    }
  }

  /// Clears all reference (non-user) tables before a reseed.
  Future<void> _clearReferenceData(Database db) async {
    await db.transaction((txn) async {
      for (final table in _referenceTablesToClear) {
        await txn.delete(table);
      }
    });
  }

  /// All reference tables that are cleared and reseeded on content version change.
  static const List<String> _referenceTablesToClear = [
    'related_content',
    'content_tags',
    'tags',
    'educational_facts',
    'collection_items',
    'collections',
    'search_aliases',
    'unit_information',
    'units',
    'categories',
    'currencies',
    'content_version',
    'schema_version',
  ];

  /// Seeds all reference data into the database in a single transaction.
  Future<void> _seedAllData(Database db) async {
    debugPrint('[DatabaseService] Seeding reference data…');
    final stopwatch = Stopwatch()..start();

    await db.transaction((txn) async {
      await _seedCategories(txn);
      await _seedUnits(txn);
      await _seedSearchAliases(txn);
      await _seedCollections(txn);
      await _seedCollectionItems(txn);
      await _seedCurrencies(txn);
      await _seedEducationalFacts(txn);
      await _seedUnitInformation(txn);
      await _seedTagsAndTaxonomy(txn);
      await _seedRelatedContentNetwork(txn);
    });

    stopwatch.stop();
    debugPrint('[DatabaseService] Seeding complete in ${stopwatch.elapsedMilliseconds}ms');
  }

  /// Writes the current schema and content versions to the database.
  Future<void> _writeVersions(Database db) async {
    final now = DateTime.now().toIso8601String();

    await db.transaction((txn) async {
      await txn.insert('schema_version', {
        'version': MigrationService.currentSchemaVersion,
        'applied_at': now,
        'description': 'Initial schema — MS Unit Converter v2.3.0',
      }, conflictAlgorithm: ConflictAlgorithm.replace);

      await txn.insert('content_version', {
        'id': 1,
        'version': _contentVersion,
        'generated_at': now,
        'source_hash': _contentHash,
      }, conflictAlgorithm: ConflictAlgorithm.replace);
    });
  }

  /// A simple hash of the content version string — used as a lightweight
  /// fingerprint. Replaced by a real file hash in Phase 2 (JSON source).
  String get _contentHash {
    var hash = 0;
    for (final rune in _contentVersion.runes) {
      hash = (hash * 31 + rune) & 0x7FFFFFFF;
    }
    return hash.toRadixString(16).padLeft(8, '0');
  }

  // ─── Seeders ───────────────────────────────────────────────────────────────

  /// Seeds the [categories] table from [UnitCategory] enum + [converterRegistry].
  Future<void> _seedCategories(Transaction txn) async {
    var sortOrder = 0;
    for (final category in UnitCategory.values) {
      final config = converterRegistry[category];
      await txn.insert(
        'categories',
        {
          'id': category.name,
          'display_name': category.displayName,
          'description': category.description,
          'group_name': config?.group ?? 'Other',
          'emoji': category.icon,
          'display_order': sortOrder++,
          'is_featured': _featuredCategories.contains(category) ? 1 : 0,
          'is_hidden': 0,
          'search_weight': 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${UnitCategory.values.length} categories');
  }

  /// Categories shown as "popular" or pinned on the home screen.
  static const Set<UnitCategory> _featuredCategories = {
    UnitCategory.length,
    UnitCategory.weight,
    UnitCategory.temperature,
    UnitCategory.area,
    UnitCategory.volume,
    UnitCategory.speed,
    UnitCategory.data,
    UnitCategory.time,
    UnitCategory.energy,
    UnitCategory.pressure,
  };

  /// Seeds the [units] table from [unitsData].
  Future<void> _seedUnits(Transaction txn) async {
    var totalUnits = 0;
    for (final entry in unitsData.entries) {
      var sortOrder = 0;
      for (final unit in entry.value) {
        await txn.insert(
          'units',
          {
            'category_id': entry.key.name,
            'name': unit.name,
            'symbol': unit.symbol,
            'to_base': unit.toBase,
            'is_special_case': unit.isSpecialCase ? 1 : 0,
            'group_name': unit.group,
            'display_order': sortOrder++,
            'is_featured': 0,
            'is_hidden': 0,
            'search_weight': 100,
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        totalUnits++;
      }
    }
    debugPrint('[DatabaseService]   ↳ $totalUnits units');
  }

  /// Seeds [search_aliases] from [SearchHelper._aliases] and currency aliases.
  Future<void> _seedSearchAliases(Transaction txn) async {
    var count = 0;
    for (final entry in _searchAliasMap.entries) {
      await txn.insert(
        'search_aliases',
        {
          'keyword': entry.key,
          'canonical': entry.value,
          'unit_id': null,
          'category_id': null,
          'priority': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      count++;
    }
    debugPrint('[DatabaseService]   ↳ $count search aliases');
  }

  /// Mirrors SearchHelper._aliases + currency aliases for the database.
  static const Map<String, String> _searchAliasMap = {
    'metre': 'Meter',
    'metres': 'Meter',
    'meters': 'Meter',
    'm': 'Meter',
    'km': 'Kilometer',
    'kilometre': 'Kilometer',
    'kilometres': 'Kilometer',
    'kilometers': 'Kilometer',
    'cm': 'Centimeter',
    'centimetre': 'Centimeter',
    'centimetres': 'Centimeter',
    'mm': 'Millimeter',
    'millimetre': 'Millimeter',
    'millimetres': 'Millimeter',
    'nm': 'Nanometer',
    'μm': 'Micrometer',
    'ft': 'Foot',
    'feet': 'Foot',
    'in': 'Inch',
    'inches': 'Inch',
    'mi': 'Mile',
    'miles': 'Mile',
    'yd': 'Yard',
    'yards': 'Yard',
    'nmi': 'Nautical Mile',
    'kg': 'Kilogram',
    'kilos': 'Kilogram',
    'kilogramme': 'Kilogram',
    'g': 'Gram',
    'grams': 'Gram',
    'mg': 'Milligram',
    'lb': 'Pound',
    'lbs': 'Pound',
    'pound': 'Pound',
    'oz': 'Ounce',
    'ounces': 'Ounce',
    'stone': 'Stone',
    'st': 'Stone',
    'l': 'Liter',
    'litre': 'Liter',
    'litres': 'Liter',
    'liters': 'Liter',
    'ml': 'Milliliter',
    'millilitre': 'Milliliter',
    'gal': 'Gallon (US)',
    'gallon': 'Gallon (US)',
    'celsius': 'Celsius',
    'centigrade': 'Celsius',
    'fahrenheit': 'Fahrenheit',
    'kelvin': 'Kelvin',
    'temp': 'Temperature',
    'kph': 'Kilometers per Hour',
    'kmh': 'Kilometers per Hour',
    'mph': 'Miles per Hour',
    'knots': 'Knot',
    'byte': 'Byte',
    'bytes': 'Byte',
    'kb': 'Kilobyte',
    'mb': 'Megabyte',
    'gb': 'Gigabyte',
    'tb': 'Terabyte',
    'pb': 'Petabyte',
    's': 'Second',
    'sec': 'Second',
    'secs': 'Second',
    'seconds': 'Second',
    'min': 'Minute',
    'mins': 'Minute',
    'hr': 'Hour',
    'hrs': 'Hour',
    'hours': 'Hour',
    'day': 'Day',
    'days': 'Day',
    'week': 'Week',
    'weeks': 'Week',
    'dollar': 'US Dollar',
    'dollars': 'US Dollar',
    'euro': 'Euro',
    'euros': 'Euro',
    'pound sterling': 'British Pound',
    'yen': 'Japanese Yen',
    'rupee': 'Pakistani Rupee',
    'pkr': 'Pakistani Rupee',
    'inr': 'Indian Rupee',
    'deg': 'Degree',
    'degrees': 'Degree',
    'rad': 'Radian',
    'radians': 'Radian',
    'pascal': 'Pascal',
    'pa': 'Pascal',
    'kpa': 'Kilopascal',
    'bar': 'Bar',
    'psi': 'PSI',
    'atm': 'Atmosphere',
    'j': 'Joule',
    'joules': 'Joule',
    'kj': 'Kilojoule',
    'kwh': 'Kilowatt-hour',
    'cal': 'Calorie',
    'calories': 'Calorie',
    'w': 'Watt',
    'watts': 'Watt',
    'kw': 'Kilowatt',
    'mw': 'Megawatt',
    'hp': 'Horsepower',
    'n': 'Newton',
    'newtons': 'Newton',
    'hz': 'Hertz',
    'khz': 'Kilohertz',
    'mhz': 'Megahertz',
    'ghz': 'Gigahertz',
    'kilowatts': 'Kilowatt',
    'megawatts': 'Megawatt',
    'gw': 'Gigawatt',
    'gigawatts': 'Gigawatt',
    'horsepower': 'Horsepower',
    'kilojoules': 'Kilojoule',
    'mj': 'Megajoule',
    'megajoules': 'Megajoule',
    'kcal': 'Kilocalorie',
    'kilocalories': 'Kilocalorie',
    'btu': 'BTU',
    'btus': 'BTU',
    'wh': 'Watt-hour',
    'mwh': 'Megawatt-hour',
    'ev': 'Electronvolt',
    'hertz': 'Hertz',
    'v': 'Volt',
    'volts': 'Volt',
    'mv': 'Millivolt',
    'kv': 'Kilovolt',
    'a': 'Ampere',
    'amps': 'Ampere',
    'ampere': 'Ampere',
    'ma': 'Milliampere',
    'ka': 'Kiloampere',
    'ohm': 'Ohm',
    'ohms': 'Ohm',
    'kohm': 'Kilohm',
    'mohm': 'Megohm',
    'pf': 'Picofarad',
    'nf': 'Nanofarad',
    'uf': 'Microfarad',
    'farad': 'Farad',
    'henry': 'Henry',
    'mh': 'Millihenry',
    'uh': 'Microhenry',
    'coulomb': 'Coulomb',
    'coulombs': 'Coulomb',
    'mah': 'Milliampere-hour',
    'ah': 'Ampere-hour',
    'siemens': 'Siemens',
    'lx': 'Lux',
    'lux': 'Lux',
    'lm': 'Lumen',
    'lumens': 'Lumen',
    'cd': 'Candela',
    'candela': 'Candela',
    'nit': 'Nit',
    'nits': 'Nit',
    'fl': 'Foot-lambert',
    'klx': 'Kilolux',
    'fc': 'Foot-candle',
    'atmospheres': 'Atmosphere',
    'torr': 'Torr',
    'mbar': 'Millibar',
    'millibar': 'Millibar',
    'mpa': 'Megapascal',
    'gpa': 'Gigapascal',
    'newton': 'Newton',
    'kn': 'Kilonewton',
    'lbf': 'Pound-force',
    'dyn': 'Dyne',
    'dyne': 'Dyne',
    'nm_torque': 'Newton-meter',
    'ft_lb': 'Foot-pound',
    'rpm': 'Revolution per Minute',
    'rps': 'Revolution per Second',
    'rad/s': 'Radian per Second',
    'deg/s': 'Degree per Second',
    'm/s': 'Meter per Second',
    'm/s2': 'Meter per Second Squared',
    'ft/s2': 'Foot per Second Squared',
    'g_accel': 'Standard Gravity',
    'au': 'Astronomical Unit',
    'ly': 'Light-year',
    'lightyears': 'Light-year',
    'pc': 'Parsec',
    'parsecs': 'Parsec',
    'kpc': 'Kiloparsec',
    'mpc': 'Megaparsec',
    'bpm': 'Beats per Minute',
    'bps': 'Beats per Second',
    'mg/dl': 'Milligrams per Deciliter',
    'mmol/l': 'Millimoles per Liter',
    'mmhg': 'Millimeters of Mercury',
    'bmi': 'Body Mass Index',
    'db': 'Decibel',
    'decibel': 'Decibel',
    'decibels': 'Decibel',
    'ppm': 'Parts per Million',
    'bq': 'Becquerel',
    'becquerel': 'Becquerel',
    'ci': 'Curie',
    'curie': 'Curie',
    'mci': 'Millicurie',
    'gy': 'Gray',
    'gray': 'Gray',
    'sv': 'Sievert',
    'sievert': 'Sievert',
    'msv': 'Millisievert',
    'usv': 'Microsievert',
    'rem': 'Rem',
    'roentgen': 'Roentgen',
    'mroentgen': 'Milliroentgen',
    't': 'Tesla',
    'tesla': 'Tesla',
    'mt': 'Millitesla',
    'ut': 'Microtesla',
    'gauss': 'Gauss',
    'wb': 'Weber',
    'weber': 'Weber',
    'mwb': 'Milliweber',
    'maxwell': 'Maxwell',
    'mol': 'Mole',
    'moles': 'Mole',
    'mol/l': 'Mole per Liter',
    'g/l': 'Gram per Liter',
    'w/m-k': 'W/(m·K)',
    'c/w': '°C/W',
    'fps': 'Feet per Second',
    'mpg': 'Miles per Gallon (US)',
    'l/100km': 'Liters per 100 Kilometers',
    'cgs': 'Centimeter-Gram-Second',
    'mks': 'Meter-Kilogram-Second',
    'si': 'International System of Units',
    'dwt': 'Pennyweight',
    'sq_m': 'Square Meter',
    'sq_ft': 'Square Foot',
    'sq_mi': 'Square Mile',
    'cu_m': 'Cubic Meter',
    'cu_ft': 'Cubic Foot',
  };

  /// Seeds the [collections] table from [predefinedCollections].
  Future<void> _seedCollections(Transaction txn) async {
    var sortOrder = 0;
    for (final col in predefinedCollections) {
      await txn.insert(
        'collections',
        {
          'id': col.id,
          'name': col.name,
          'emoji': col.emoji,
          'description': col.description,
          'display_order': sortOrder++,
          'is_featured': 0,
          'is_hidden': 0,
          'search_weight': 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${predefinedCollections.length} collections');
  }

  /// Seeds [collection_items] from [predefinedCollections].
  Future<void> _seedCollectionItems(Transaction txn) async {
    var count = 0;
    for (final col in predefinedCollections) {
      var sortOrder = 0;
      for (final category in col.categories) {
        await txn.insert(
          'collection_items',
          {
            'collection_id': col.id,
            'category_id': category.name,
            'display_order': sortOrder++,
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        count++;
      }
    }
    debugPrint('[DatabaseService]   ↳ $count collection items');
  }

  /// Seeds the [currencies] table from [allIsoCurrencies].
  Future<void> _seedCurrencies(Transaction txn) async {
    var pinOrder = 0;
    for (final entry in allIsoCurrencies) {
      final isPinned = pinnedCurrencyCodes.contains(entry.code);
      await txn.insert(
        'currencies',
        {
          'iso_code': entry.code,
          'name': entry.name,
          'symbol': entry.symbol,
          'flag': entry.flag,
          'country': entry.country,
          'decimal_digits': entry.decimalDigits,
          'fallback_rate_to_usd': entry.fallbackRateToUsd,
          'is_pinned': isPinned ? 1 : 0,
          'pin_order': isPinned ? pinOrder++ : null,
          'display_order': 0,
          'is_featured': isPinned ? 1 : 0,
          'search_weight': isPinned ? 200 : 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${allIsoCurrencies.length} currencies');
  }

  /// Seeds [educational_facts] from [didYouKnowFacts].
  Future<void> _seedEducationalFacts(Transaction txn) async {
    var sortOrder = 0;
    for (final fact in didYouKnowFacts) {
      await txn.insert(
        'educational_facts',
        {
          'emoji': fact.emoji,
          'fact': fact.fact,
          'category_id': null,
          'display_order': sortOrder++,
          'is_featured': 0,
          'is_hidden': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      sortOrder++;
    }
    debugPrint('[DatabaseService]   ↳ ${didYouKnowFacts.length} educational facts');
  }

  /// Seeds [unit_information] from `assets/data/unit_information.json`.
  Future<void> _seedUnitInformation(Transaction txn) async {
    try {
      String? jsonStr;
      try {
        jsonStr = await rootBundle.loadString('assets/data/unit_information.json');
      } catch (_) {
        final file = File('assets/data/unit_information.json');
        if (await file.exists()) {
          jsonStr = await file.readAsString();
        }
      }

      if (jsonStr == null || jsonStr.isEmpty) return;

      final decoded = jsonDecode(jsonStr) as Map<String, dynamic>;
      final unitRows = await txn.query('units', columns: ['id', 'name', 'symbol']);
      final jsonToInfo = <String, Map<String, dynamic>>{};
      for (final entry in decoded.entries) {
        jsonToInfo[entry.key.toLowerCase().replaceAll('_', ' ')] =
            entry.value as Map<String, dynamic>;
        jsonToInfo[entry.key.toLowerCase()] = entry.value as Map<String, dynamic>;
      }

      var count = 0;
      for (final r in unitRows) {
        final unitId = r['id'] as int;
        final unitName = r['name'] as String;
        final dbSymbol = r['symbol'] as String;
        final keyLower = unitName.toLowerCase();
        final keySpaced = keyLower.replaceAll('_', ' ');

        final val = jsonToInfo[keyLower] ?? jsonToInfo[keySpaced];

        final symbol = val != null ? (val['symbol'] as String? ?? dbSymbol) : dbSymbol;
        final definition = val != null
            ? (val['definition'] as String? ?? '')
            : 'The $unitName is a standard unit of measurement.';
        final history = val != null
            ? (val['history'] as String? ?? '')
            : 'Standardized unit of measurement used globally.';
        final usedFor = val != null
            ? (val['used_for'] as String? ?? '')
            : 'Measurements and calculations.';
        final examplesList = val != null
            ? ((val['examples'] as List<dynamic>?)?.map((e) => e.toString()).toList() ?? [])
            : ['1 $unitName'];

        await txn.insert(
          'unit_information',
          {
            'unit_id': unitId,
            'symbol': symbol,
            'definition': definition,
            'history': history,
            'used_for': usedFor,
            'examples': jsonEncode(examplesList),
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        count++;
      }
      debugPrint('[DatabaseService]   ↳ $count unit information records');
      debugPrint('[DatabaseService]   ↳ $count unit information records');
    } catch (e) {
      debugPrint('[DatabaseService] Error seeding unit_information: $e');
    }
  }



  /// Closes the database. Should only be called when the app is disposing.

  /// Seeds [tags] and [content_tags] for cross-cutting domain taxonomy (Phase F1).
  Future<void> _seedTagsAndTaxonomy(Transaction txn) async {
    final domainTags = [
      'metric',
      'imperial',
      'si',
      'cgs',
      'everyday',
      'science',
      'engineering',
      'medical',
      'electrical',
      'optics',
      'thermodynamics',
      'astronomy',
      'digital',
      'acoustics',
      'fluid_mechanics',
      'automotive',
    ];

    final tagMap = <String, int>{};
    for (final tagName in domainTags) {
      await txn.insert(
        'tags',
        {'name': tagName},
        conflictAlgorithm: ConflictAlgorithm.ignore,
      );
      final rows = await txn.query('tags', where: 'name = ?', whereArgs: [tagName], columns: ['id']);
      if (rows.isNotEmpty) {
        tagMap[tagName] = rows.first['id'] as int;
      }
    }

    // Category taxonomy associations
    final categoryTaxonomy = <String, List<String>>{
      'length': ['metric', 'imperial', 'si', 'everyday'],
      'weight': ['metric', 'imperial', 'si', 'everyday'],
      'temperature': ['si', 'everyday', 'thermodynamics'],
      'area': ['metric', 'imperial', 'si', 'everyday'],
      'volume': ['metric', 'imperial', 'si', 'everyday'],
      'speed': ['everyday', 'automotive', 'si'],
      'data': ['digital', 'engineering'],
      'time': ['everyday', 'science', 'si'],
      'voltage': ['electrical', 'engineering', 'si'],
      'current': ['electrical', 'engineering', 'si'],
      'resistance': ['electrical', 'engineering', 'si'],
      'capacitance': ['electrical', 'engineering', 'si'],
      'inductance': ['electrical', 'engineering', 'si'],
      'power': ['electrical', 'engineering', 'automotive', 'si'],
      'energy': ['science', 'thermodynamics', 'si'],
      'pressure': ['engineering', 'fluid_mechanics', 'si'],
      'illuminance': ['optics', 'science', 'si'],
      'luminousFlux': ['optics', 'science', 'si'],
      'bloodPressure': ['medical', 'everyday'],
      'bloodSugar': ['medical', 'everyday'],
      'heartRate': ['medical', 'everyday'],
      'bmi': ['medical', 'everyday'],
      'astronomicalLength': ['astronomy', 'science'],
      'radioactivity': ['science', 'medical'],
      'radiationDose': ['science', 'medical'],
      'soundLevel': ['acoustics', 'engineering'],
      'flowRate': ['fluid_mechanics', 'engineering'],
      'density': ['science', 'fluid_mechanics'],
      'torque': ['engineering', 'automotive'],
      'fuelEconomy': ['automotive', 'everyday'],
    };

    var count = 0;
    for (final entry in categoryTaxonomy.entries) {
      final catId = entry.key;
      for (final tagName in entry.value) {
        final tagId = tagMap[tagName];
        if (tagId != null) {
          await txn.insert(
            'content_tags',
            {
              'tag_id': tagId,
              'source_type': 'category',
              'source_id': catId,
            },
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          count++;
        }
      }
    }
    debugPrint('[DatabaseService]   ↳ ${tagMap.length} tags and $count content_tags seeded');
  }

  /// Seeds [related_content] graph edges between categories, units, and facts (Phase C).
  Future<void> _seedRelatedContentNetwork(Transaction txn) async {
    final relationships = <(String, String, String, String, String)>[
      ('category', 'length', 'category', 'area', 'child'),
      ('category', 'length', 'category', 'volume', 'child'),
      ('category', 'length', 'category', 'speed', 'related'),
      ('category', 'length', 'category', 'acceleration', 'related'),
      ('category', 'length', 'category', 'astronomicalLength', 'parent'),
      ('category', 'length', 'category', 'typography', 'sibling'),
      ('category', 'area', 'category', 'volume', 'sibling'),
      ('category', 'speed', 'category', 'acceleration', 'sibling'),
      ('category', 'speed', 'category', 'angularVelocity', 'sibling'),
      ('category', 'speed', 'category', 'pace', 'sibling'),
      ('category', 'speed', 'category', 'fuelEconomy', 'related'),
      ('category', 'angle', 'category', 'angularVelocity', 'child'),
      ('category', 'force', 'category', 'weight', 'sibling'),
      ('category', 'force', 'category', 'torque', 'child'),
      ('category', 'force', 'category', 'pressure', 'parent'),
      ('category', 'force', 'category', 'momentum', 'sibling'),
      ('category', 'force', 'category', 'energy', 'related'),
      ('category', 'weight', 'category', 'density', 'related'),
      ('category', 'weight', 'category', 'massFlowRate', 'related'),
      ('category', 'torque', 'category', 'power', 'related'),
      ('category', 'momentum', 'category', 'energy', 'sibling'),
      ('category', 'pressure', 'category', 'surfaceTension', 'related'),
      ('category', 'pressure', 'category', 'density', 'related'),
      ('category', 'energy', 'category', 'power', 'parent'),
      ('category', 'energy', 'category', 'specificHeat', 'related'),
      ('category', 'energy', 'category', 'fuelEconomy', 'related'),
      ('category', 'power', 'category', 'voltage', 'related'),
      ('category', 'power', 'category', 'heatFluxDensity', 'related'),
      ('category', 'temperature', 'category', 'specificHeat', 'parent'),
      ('category', 'temperature', 'category', 'thermalConductivity', 'sibling'),
      ('category', 'temperature', 'category', 'thermalResistance', 'sibling'),
      ('category', 'temperature', 'category', 'heatFluxDensity', 'sibling'),
      ('category', 'thermalConductivity', 'category', 'thermalResistance', 'derived'),
      ('category', 'voltage', 'category', 'current', 'sibling'),
      ('category', 'voltage', 'category', 'resistance', 'sibling'),
      ('category', 'voltage', 'category', 'power', 'sibling'),
      ('category', 'voltage', 'category', 'capacitance', 'related'),
      ('category', 'voltage', 'category', 'inductance', 'related'),
      ('category', 'current', 'category', 'electricCharge', 'child'),
      ('category', 'current', 'category', 'conductance', 'sibling'),
      ('category', 'resistance', 'category', 'conductance', 'derived'),
      ('category', 'electricCharge', 'category', 'capacitance', 'related'),
      ('category', 'magneticField', 'category', 'magneticFlux', 'parent'),
      ('category', 'inductance', 'category', 'magneticFlux', 'related'),
      ('category', 'density', 'category', 'kinematicViscosity', 'sibling'),
      ('category', 'density', 'category', 'dynamicViscosity', 'sibling'),
      ('category', 'density', 'category', 'concentration', 'related'),
      ('category', 'flowRate', 'category', 'massFlowRate', 'sibling'),
      ('category', 'flowRate', 'category', 'kinematicViscosity', 'related'),
      ('category', 'kinematicViscosity', 'category', 'dynamicViscosity', 'derived'),
      ('category', 'surfaceTension', 'category', 'dynamicViscosity', 'related'),
      ('category', 'illuminance', 'category', 'luminousFlux', 'sibling'),
      ('category', 'illuminance', 'category', 'luminousIntensity', 'sibling'),
      ('category', 'illuminance', 'category', 'luminance', 'sibling'),
      ('category', 'luminousFlux', 'category', 'luminousIntensity', 'child'),
      ('category', 'frequency', 'category', 'soundLevel', 'related'),
      ('category', 'frequency', 'category', 'wavenumber', 'sibling'),
      ('category', 'frequency', 'category', 'angularVelocity', 'related'),
      ('category', 'bloodPressure', 'category', 'heartRate', 'sibling'),
      ('category', 'bloodPressure', 'category', 'bloodSugar', 'sibling'),
      ('category', 'bloodSugar', 'category', 'bmi', 'sibling'),
      ('category', 'bmi', 'category', 'percentageRatio', 'related'),
      ('category', 'concentration', 'category', 'bloodSugar', 'parent'),
      ('category', 'shoeSize', 'category', 'clothingSize', 'sibling'),
      ('category', 'radioactivity', 'category', 'radiationDose', 'parent'),
      ('category', 'radiationDose', 'category', 'radiationExposure', 'sibling'),
      ('category', 'radioactivity', 'category', 'radiationExposure', 'child'),
      ('category', 'data', 'category', 'time', 'related'),
      ('category', 'numberBase', 'category', 'data', 'related'),
      ('category', 'length', 'unit', 'Meter', 'child'),
      ('category', 'length', 'unit', 'Kilometer', 'child'),
      ('category', 'length', 'unit', 'Foot', 'child'),
      ('category', 'length', 'unit', 'Mile', 'child'),
      ('category', 'length', 'unit', 'Inch', 'child'),
      ('category', 'length', 'unit', 'Centimeter', 'child'),
      ('category', 'length', 'unit', 'Nautical Mile', 'child'),
      ('category', 'weight', 'unit', 'Kilogram', 'child'),
      ('category', 'weight', 'unit', 'Gram', 'child'),
      ('category', 'weight', 'unit', 'Pound', 'child'),
      ('category', 'weight', 'unit', 'Ounce', 'child'),
      ('category', 'temperature', 'unit', 'Celsius', 'child'),
      ('category', 'temperature', 'unit', 'Fahrenheit', 'child'),
      ('category', 'temperature', 'unit', 'Kelvin', 'child'),
      ('category', 'area', 'unit', 'Square Meter', 'child'),
      ('category', 'area', 'unit', 'Acre', 'child'),
      ('category', 'area', 'unit', 'Hectare', 'child'),
      ('category', 'area', 'unit', 'Square Foot', 'child'),
      ('category', 'volume', 'unit', 'Liter', 'child'),
      ('category', 'volume', 'unit', 'Gallon (US)', 'child'),
      ('category', 'volume', 'unit', 'Cubic Meter', 'child'),
      ('category', 'volume', 'unit', 'Milliliter', 'child'),
      ('category', 'speed', 'unit', 'Kilometers per Hour', 'child'),
      ('category', 'speed', 'unit', 'Miles per Hour', 'child'),
      ('category', 'speed', 'unit', 'Knot', 'child'),
      ('category', 'time', 'unit', 'Second', 'child'),
      ('category', 'time', 'unit', 'Minute', 'child'),
      ('category', 'time', 'unit', 'Hour', 'child'),
      ('category', 'time', 'unit', 'Day', 'child'),
      ('category', 'time', 'unit', 'Year', 'child'),
      ('category', 'energy', 'unit', 'Joule', 'child'),
      ('category', 'energy', 'unit', 'Calorie', 'child'),
      ('category', 'energy', 'unit', 'Kilowatt-hour', 'child'),
      ('category', 'energy', 'unit', 'Electronvolt', 'child'),
      ('category', 'power', 'unit', 'Watt', 'child'),
      ('category', 'power', 'unit', 'Horsepower', 'child'),
      ('category', 'power', 'unit', 'Kilowatt', 'child'),
      ('category', 'pressure', 'unit', 'Pascal', 'child'),
      ('category', 'pressure', 'unit', 'Bar', 'child'),
      ('category', 'pressure', 'unit', 'PSI', 'child'),
      ('category', 'pressure', 'unit', 'Atmosphere', 'child'),
      ('category', 'pressure', 'unit', 'mmHg', 'child'),
      ('category', 'force', 'unit', 'Newton', 'child'),
      ('category', 'force', 'unit', 'Pound-force', 'child'),
      ('category', 'force', 'unit', 'Dyne', 'child'),
      ('category', 'frequency', 'unit', 'Hertz', 'child'),
      ('category', 'frequency', 'unit', 'Kilohertz', 'child'),
      ('category', 'frequency', 'unit', 'Megahertz', 'child'),
      ('category', 'frequency', 'unit', 'Gigahertz', 'child'),
      ('category', 'voltage', 'unit', 'Volt', 'child'),
      ('category', 'voltage', 'unit', 'Millivolt', 'child'),
      ('category', 'voltage', 'unit', 'Kilovolt', 'child'),
      ('category', 'current', 'unit', 'Ampere', 'child'),
      ('category', 'current', 'unit', 'Milliampere', 'child'),
      ('category', 'resistance', 'unit', 'Ohm', 'child'),
      ('category', 'capacitance', 'unit', 'Farad', 'child'),
      ('category', 'inductance', 'unit', 'Henry', 'child'),
      ('category', 'electricCharge', 'unit', 'Coulomb', 'child'),
      ('category', 'conductance', 'unit', 'Siemens', 'child'),
      ('category', 'illuminance', 'unit', 'Lux', 'child'),
      ('category', 'luminousFlux', 'unit', 'Lumen', 'child'),
      ('category', 'luminousIntensity', 'unit', 'Candela', 'child'),
      ('category', 'density', 'unit', 'Gram per Cubic Centimeter', 'child'),
      ('category', 'torque', 'unit', 'Foot-pound', 'child'),
      ('category', 'angle', 'unit', 'Degree', 'child'),
      ('category', 'angle', 'unit', 'Radian', 'child'),
      ('category', 'data', 'unit', 'Byte', 'child'),
      ('category', 'data', 'unit', 'Gigabyte', 'child'),
      ('category', 'data', 'unit', 'Megabyte', 'child'),
      ('category', 'data', 'unit', 'Terabyte', 'child'),
      ('unit', 'Meter', 'unit', 'Kilometer', 'sibling'),
      ('unit', 'Meter', 'unit', 'Centimeter', 'sibling'),
      ('unit', 'Meter', 'unit', 'Millimeter', 'sibling'),
      ('unit', 'Meter', 'unit', 'Foot', 'related'),
      ('unit', 'Meter', 'unit', 'Yard', 'related'),
      ('unit', 'Meter', 'unit', 'Mile', 'related'),
      ('unit', 'Meter', 'unit', 'Nautical Mile', 'related'),
      ('unit', 'Kilometer', 'unit', 'Mile', 'related'),
      ('unit', 'Foot', 'unit', 'Inch', 'child'),
      ('unit', 'Foot', 'unit', 'Yard', 'parent'),
      ('unit', 'Mile', 'unit', 'Nautical Mile', 'sibling'),
      ('unit', 'Centimeter', 'unit', 'Inch', 'related'),
      ('unit', 'Millimeter', 'unit', 'Micrometer', 'parent'),
      ('unit', 'Kilometer', 'unit', 'Meter', 'parent'),
      ('unit', 'Kilogram', 'unit', 'Gram', 'parent'),
      ('unit', 'Kilogram', 'unit', 'Milligram', 'parent'),
      ('unit', 'Kilogram', 'unit', 'Pound', 'related'),
      ('unit', 'Pound', 'unit', 'Ounce', 'child'),
      ('unit', 'Gram', 'unit', 'Milligram', 'parent'),
      ('unit', 'Ounce', 'unit', 'Gram', 'related'),
      ('unit', 'Square Meter', 'unit', 'Square Kilometer', 'child'),
      ('unit', 'Square Meter', 'unit', 'Square Foot', 'related'),
      ('unit', 'Acre', 'unit', 'Hectare', 'sibling'),
      ('unit', 'Liter', 'unit', 'Milliliter', 'parent'),
      ('unit', 'Liter', 'unit', 'Cubic Meter', 'child'),
      ('unit', 'Liter', 'unit', 'Gallon (US)', 'related'),
      ('unit', 'Gallon (US)', 'unit', 'Gallon (UK)', 'sibling'),
      ('unit', 'Gallon (US)', 'unit', 'Pint (US)', 'parent'),
      ('unit', 'Fluid Ounce (US)', 'unit', 'Milliliter', 'related'),
      ('unit', 'Kilometers per Hour', 'unit', 'Miles per Hour', 'sibling'),
      ('unit', 'Knot', 'unit', 'Miles per Hour', 'related'),
      ('unit', 'Second', 'unit', 'Minute', 'child'),
      ('unit', 'Minute', 'unit', 'Hour', 'child'),
      ('unit', 'Hour', 'unit', 'Day', 'child'),
      ('unit', 'Pascal', 'unit', 'Bar', 'sibling'),
      ('unit', 'Pascal', 'unit', 'PSI', 'related'),
      ('unit', 'Pascal', 'unit', 'Atmosphere', 'related'),
      ('unit', 'Bar', 'unit', 'Atmosphere', 'sibling'),
      ('unit', 'PSI', 'unit', 'Atmosphere', 'related'),
      ('unit', 'mmHg', 'unit', 'Atmosphere', 'related'),
      ('unit', 'Joule', 'unit', 'Calorie', 'related'),
      ('unit', 'Joule', 'unit', 'Kilowatt-hour', 'related'),
      ('unit', 'Joule', 'unit', 'Electronvolt', 'child'),
      ('unit', 'Joule', 'unit', 'BTU', 'related'),
      ('unit', 'Calorie', 'unit', 'Kilocalorie', 'child'),
      ('unit', 'Kilowatt-hour', 'unit', 'Watt-hour', 'parent'),
      ('unit', 'Watt', 'unit', 'Kilowatt', 'child'),
      ('unit', 'Watt', 'unit', 'Horsepower', 'related'),
      ('unit', 'Watt', 'unit', 'Megawatt', 'child'),
      ('unit', 'Kilowatt', 'unit', 'Horsepower', 'related'),
      ('unit', 'Volt', 'unit', 'Millivolt', 'parent'),
      ('unit', 'Volt', 'unit', 'Kilovolt', 'child'),
      ('unit', 'Ampere', 'unit', 'Milliampere', 'parent'),
      ('unit', 'Hertz', 'unit', 'Kilohertz', 'child'),
      ('unit', 'Hertz', 'unit', 'Megahertz', 'child'),
      ('unit', 'Newton', 'unit', 'Joule', 'derived'),
      ('unit', 'Newton', 'unit', 'Pascal', 'derived'),
      ('unit', 'Newton', 'unit', 'Kilogram', 'related'),
      ('unit', 'Newton', 'unit', 'Meter', 'related'),
      ('unit', 'Newton', 'unit', 'Pound-force', 'sibling'),
      ('unit', 'Pascal', 'unit', 'Newton', 'derived'),
      ('unit', 'Pascal', 'unit', 'Square Meter', 'derived'),
      ('unit', 'Joule', 'unit', 'Newton', 'derived'),
      ('unit', 'Joule', 'unit', 'Meter', 'derived'),
      ('unit', 'Joule', 'unit', 'Watt', 'derived'),
      ('unit', 'Watt', 'unit', 'Joule', 'derived'),
      ('unit', 'Watt', 'unit', 'Second', 'derived'),
      ('unit', 'Volt', 'unit', 'Ampere', 'related'),
      ('unit', 'Volt', 'unit', 'Ohm', 'related'),
      ('unit', 'Volt', 'unit', 'Watt', 'derived'),
      ('unit', 'Ampere', 'unit', 'Coulomb', 'derived'),
      ('unit', 'Ampere', 'unit', 'Second', 'derived'),
      ('unit', 'Ohm', 'unit', 'Volt', 'derived'),
      ('unit', 'Ohm', 'unit', 'Ampere', 'derived'),
      ('unit', 'Ohm', 'unit', 'Siemens', 'derived'),
      ('unit', 'Hertz', 'unit', 'Second', 'derived'),
      ('unit', 'Celsius', 'unit', 'Fahrenheit', 'sibling'),
      ('unit', 'Celsius', 'unit', 'Kelvin', 'sibling'),
      ('unit', 'Lux', 'unit', 'Lumen', 'derived'),
      ('unit', 'Lumen', 'unit', 'Candela', 'derived'),
      ('unit', 'Byte', 'unit', 'Kilobyte', 'child'),
      ('unit', 'Byte', 'unit', 'Megabyte', 'child'),
      ('unit', 'Byte', 'unit', 'Gigabyte', 'child'),
      ('unit', 'Gigabyte', 'unit', 'Terabyte', 'child'),
      ('unit', 'Bit', 'unit', 'Byte', 'parent'),
      ('category', 'length', 'fact', '0', 'related'),
      ('category', 'weight', 'fact', '1', 'related'),
      ('category', 'temperature', 'fact', '2', 'related'),
      ('category', 'area', 'fact', '3', 'related'),
      ('category', 'volume', 'fact', '4', 'related'),
      ('category', 'speed', 'fact', '5', 'related'),
      ('category', 'energy', 'fact', '6', 'related'),
      ('category', 'power', 'fact', '7', 'related'),
      ('category', 'pressure', 'fact', '8', 'related'),
      ('category', 'time', 'fact', '9', 'related'),
      ('category', 'force', 'fact', '10', 'related'),
      ('category', 'voltage', 'fact', '11', 'related'),
      ('category', 'current', 'fact', '12', 'related'),
      ('category', 'frequency', 'fact', '13', 'related'),
      ('category', 'angle', 'fact', '14', 'related'),
      ('category', 'data', 'fact', '15', 'related'),
      ('category', 'density', 'fact', '16', 'related'),
      ('category', 'torque', 'fact', '17', 'related'),
    ];

    var count = 0;
    for (var i = 0; i < relationships.length; i++) {
      final (srcType, srcId, tgtType, tgtId, relType) = relationships[i];
      await txn.insert(
        'related_content',
        {
          'source_type': srcType,
          'source_id': srcId,
          'target_type': tgtType,
          'target_id': tgtId,
          'relationship_type': relType,
          'display_order': i,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      count++;
    }
    debugPrint('[DatabaseService]   ↳ $count related_content edges seeded');
  }

  Future<void> close() async {
    await _db?.close();
    _db = null;
    _initialized = false;
    debugPrint('[DatabaseService] Closed');
  }

  /// Deletes the database file. For development/testing only.
  ///
  /// Call [initialize] again to recreate and reseed.
  @visibleForTesting
  Future<void> deleteDatabase() async {
    await close();
    final dbPath = await _resolveDbPath();
    final file = File(dbPath);
    if (await file.exists()) {
      await file.delete();
      debugPrint('[DatabaseService] Database deleted: $dbPath');
    }
  }
}
