/// Singleton SQLite database manager for MS Unit Converter.
///
/// Responsibilities:
/// - Open the SQLite database (creating schema on first launch via [MigrationService]).
/// - Check [_contentVersion] against the stored version; reseed from Dart data
///   if the content has changed (new app release with updated data).
/// - Expose a single [Database] instance to all repositories via [database].
///
/// ## Phase 1 Architecture
/// The database is seeded **at runtime** from existing Dart data structures
/// on first launch. This avoids any build-tool or binary-asset dependency.
///
/// ## Phase 2 Architecture (future)
/// The database will be shipped as a pre-built binary asset
/// (`assets/database/unit_converter.db`) generated by `tools/build_database.dart`
/// from JSON content files. `DatabaseService` will copy the asset to the
/// documents directory and open it from there instead of seeding at runtime.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

import '../core/constants.dart';
import 'migration_service.dart';
import '../data/collections_data.dart';
import '../data/converter_config.dart';
import '../data/currencies_data.dart';
import '../data/did_you_know.dart';
import '../data/units_data.dart';

/// Current content version — matches the app release that last changed reference data.
/// Increment this when any reference data changes (units, currencies, facts, etc.)
/// to trigger an automatic reseed on the next launch.
const String _contentVersion = '2.3.0';

/// SQLite database filename stored in the app documents directory.
const String _dbFileName = DatabaseConstants.databaseFileName;

/// Sole owner of SQLite database lifecycle.
///
/// ## ARCHITECTURE GUARDRAILS
/// Responsibilities:
/// - Copy pre-populated asset database on first launch
/// - Open and manage database connection
/// - Run schema migrations via [MigrationService]
/// - Handle content version management
///
/// **STRICT RULE**: Never implement unit conversions, business logic, or UI state here.
class DatabaseService {
  DatabaseService._();

  /// The singleton instance.
  static final DatabaseService instance = DatabaseService._();

  Database? _db;
  bool _initialized = false;

  /// Returns whether the database has been initialized and is open.
  bool get isInitialized => _initialized && _db != null && _db!.isOpen;

  /// Returns the open [Database] instance.
  ///
  /// Throws a [StateError] if [initialize] has not been called first.
  Database get database {
    if (!isInitialized) {
      throw StateError(
        'DatabaseService not initialized. '
        'Call DatabaseService.instance.initialize() before accessing the database.',
      );
    }
    return _db!;
  }

  /// Initializes the database: opens it, runs migrations, and seeds data if needed.
  ///
  /// Safe to call multiple times — subsequent calls are no-ops.
  /// First checks if the pre-populated asset database exists and copies it to
  /// the app documents directory if no database exists yet.
  Future<void> initialize() async {
    if (_initialized && _db != null && _db!.isOpen) return;

    if (!kIsWeb && (Platform.isLinux || Platform.isWindows || Platform.isMacOS)) {
      sqfliteFfiInit();
      databaseFactory = databaseFactoryFfi;
    }

    final stopwatch = Stopwatch()..start();

    try {
      final dbPath = await _resolveDbPath();
      final dbFile = File(dbPath);

      if (!await dbFile.exists()) {
        await _copyPrePopulatedDatabase(dbPath);
      }

      debugPrint('[DatabaseService] Opening database at: $dbPath');

      _db = await openDatabase(
        dbPath,
        version: MigrationService.currentSchemaVersion,
        onCreate: (db, version) async {
          debugPrint('[DatabaseService] Creating schema (version $version)');
          await MigrationService.createSchema(db);
          await _clearReferenceData(db);
          await _seedAllData(db);
          await _writeVersions(db);
        },
        onUpgrade: (db, oldVersion, newVersion) async {
          debugPrint(
            '[DatabaseService] Upgrading schema: $oldVersion → $newVersion',
          );
          await MigrationService.upgrade(db, oldVersion, newVersion);
          // After a schema upgrade, check if content also needs refreshing.
          await _reseedIfContentChanged(db);
        },
        onOpen: (db) async {
          debugPrint('[DatabaseService] Database opened — checking content version');
          await _reseedIfContentChanged(db);
        },
      );

      _initialized = true;
      stopwatch.stop();

      if (kDebugMode) {
        final sizeKb = await dbFile.exists()
            ? (await dbFile.length() / 1024).toStringAsFixed(2)
            : '0.00';
        debugPrint(
          '[DatabaseService] Initialized in ${stopwatch.elapsedMilliseconds}ms — File size: $sizeKb KB',
        );
      }
    } catch (e, st) {
      stopwatch.stop();
      debugPrint('[DatabaseService] Initialization error: $e\n$st');
      rethrow;
    }
  }

  /// Copies the pre-populated SQLite asset database from [rootBundle] to [targetPath].
  ///
  /// Returns `true` if successfully copied, `false` otherwise (e.g. asset missing in tests).
  Future<bool> _copyPrePopulatedDatabase(String targetPath) async {
    try {
      debugPrint('[DatabaseService] Copying pre-populated asset database to: $targetPath');
      final file = File(targetPath);
      await file.parent.create(recursive: true);

      final data = await rootBundle.load(DatabaseConstants.databaseAssetPath);
      final bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await file.writeAsBytes(bytes, flush: true);
      debugPrint('[DatabaseService] Pre-populated database asset copied (${bytes.length} bytes)');
      return true;
    } catch (e) {
      debugPrint(
        '[DatabaseService] Asset database copy omitted/failed (falling back to dynamic seed): $e',
      );
      return false;
    }
  }

  /// Seeds all reference data and writes version metadata into [db].
  ///
  /// Exposed for [tools/build_database.dart] to generate pre-populated binaries.
  static Future<void> seedDatabase(Database db) async {
    await MigrationService.createSchema(db);
    await instance._clearReferenceData(db);
    await instance._seedAllData(db);
    await instance._writeVersions(db);
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  /// Resolves the absolute file path for storing the SQLite database file.
  Future<String> _resolveDbPath() async {
    try {
      final docsDir = await getApplicationDocumentsDirectory();
      return path.join(docsDir.path, _dbFileName);
    } catch (_) {
      // Fallback for headless unit test runner where path_provider plugin is unmocked
      return path.join(Directory.systemTemp.path, _dbFileName);
    }
  }

  /// Checks if the content version in the DB matches [_contentVersion].
  /// Reseeds reference data if the version has changed.
  Future<void> _reseedIfContentChanged(Database db) async {
    final storedVersion = await _readContentVersion(db);
    if (storedVersion == _contentVersion) {
      debugPrint('[DatabaseService] Content version current ($_contentVersion) — skip reseed');
      return;
    }

    debugPrint(
      '[DatabaseService] Content version changed: ${storedVersion ?? 'none'} → $_contentVersion — reseeding reference tables…',
    );
    await _clearReferenceData(db);
    await _seedAllData(db);
    await _writeVersions(db);
  }

  /// Reads the stored content version from the [content_version] table.
  Future<String?> _readContentVersion(Database db) async {
    try {
      final rows = await db.query('content_version', limit: 1);
      if (rows.isEmpty) return null;
      return rows.first['version'] as String?;
    } catch (_) {
      return null;
    }
  }

  /// Clears all reference (non-user) tables before a reseed.
  Future<void> _clearReferenceData(Database db) async {
    await db.transaction((txn) async {
      for (final table in _referenceTablesToClear) {
        await txn.delete(table);
      }
    });
  }

  /// All reference tables that are cleared and reseeded on content version change.
  static const List<String> _referenceTablesToClear = [
    'related_content',
    'content_tags',
    'tags',
    'educational_facts',
    'collection_items',
    'collections',
    'search_aliases',
    'unit_information',
    'units',
    'categories',
    'currencies',
    'content_version',
    'schema_version',
  ];

  /// Seeds all reference data into the database in a single transaction.
  Future<void> _seedAllData(Database db) async {
    debugPrint('[DatabaseService] Seeding reference data…');
    final stopwatch = Stopwatch()..start();

    await db.transaction((txn) async {
      await _seedCategories(txn);
      await _seedUnits(txn);
      await _seedSearchAliases(txn);
      await _seedCollections(txn);
      await _seedCollectionItems(txn);
      await _seedCurrencies(txn);
      await _seedEducationalFacts(txn);
      await _seedUnitInformation(txn);
      await _seedTagsAndTaxonomy(txn);
      await _seedRelatedContentNetwork(txn);
    });

    stopwatch.stop();
    debugPrint('[DatabaseService] Seeding complete in ${stopwatch.elapsedMilliseconds}ms');
  }

  /// Writes the current schema and content versions to the database.
  Future<void> _writeVersions(Database db) async {
    final now = DateTime.now().toIso8601String();

    await db.transaction((txn) async {
      await txn.insert('schema_version', {
        'version': MigrationService.currentSchemaVersion,
        'applied_at': now,
        'description': 'Initial schema — MS Unit Converter v2.3.0',
      }, conflictAlgorithm: ConflictAlgorithm.replace);

      await txn.insert('content_version', {
        'id': 1,
        'version': _contentVersion,
        'generated_at': now,
        'source_hash': _contentHash,
      }, conflictAlgorithm: ConflictAlgorithm.replace);
    });
  }

  /// A simple hash of the content version string — used as a lightweight
  /// fingerprint. Replaced by a real file hash in Phase 2 (JSON source).
  String get _contentHash {
    var hash = 0;
    for (final rune in _contentVersion.runes) {
      hash = (hash * 31 + rune) & 0x7FFFFFFF;
    }
    return hash.toRadixString(16).padLeft(8, '0');
  }

  // ─── Seeders ───────────────────────────────────────────────────────────────

  /// Seeds the [categories] table from [UnitCategory] enum + [converterRegistry].
  Future<void> _seedCategories(Transaction txn) async {
    var sortOrder = 0;
    for (final category in UnitCategory.values) {
      final config = converterRegistry[category];
      await txn.insert(
        'categories',
        {
          'id': category.name,
          'display_name': category.displayName,
          'description': category.description,
          'group_name': config?.group ?? 'Other',
          'emoji': category.icon,
          'display_order': sortOrder++,
          'is_featured': _featuredCategories.contains(category) ? 1 : 0,
          'is_hidden': 0,
          'search_weight': 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${UnitCategory.values.length} categories');
  }

  /// Categories shown as "popular" or pinned on the home screen.
  static const Set<UnitCategory> _featuredCategories = {
    UnitCategory.length,
    UnitCategory.weight,
    UnitCategory.temperature,
    UnitCategory.area,
    UnitCategory.volume,
    UnitCategory.speed,
    UnitCategory.data,
    UnitCategory.time,
    UnitCategory.energy,
    UnitCategory.pressure,
  };

  /// Seeds the [units] table from [unitsData].
  Future<void> _seedUnits(Transaction txn) async {
    var totalUnits = 0;
    for (final entry in unitsData.entries) {
      var sortOrder = 0;
      for (final unit in entry.value) {
        await txn.insert(
          'units',
          {
            'category_id': entry.key.name,
            'name': unit.name,
            'symbol': unit.symbol,
            'to_base': unit.toBase,
            'is_special_case': unit.isSpecialCase ? 1 : 0,
            'group_name': unit.group,
            'display_order': sortOrder++,
            'is_featured': 0,
            'is_hidden': 0,
            'search_weight': 100,
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        totalUnits++;
      }
    }
    debugPrint('[DatabaseService]   ↳ $totalUnits units');
  }

  /// Seeds [search_aliases] from [SearchHelper._aliases] and currency aliases.
  Future<void> _seedSearchAliases(Transaction txn) async {
    var count = 0;
    for (final entry in _searchAliasMap.entries) {
      await txn.insert(
        'search_aliases',
        {
          'keyword': entry.key,
          'canonical': entry.value,
          'unit_id': null,
          'category_id': null,
          'priority': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      count++;
    }
    debugPrint('[DatabaseService]   ↳ $count search aliases');
  }

  /// Mirrors SearchHelper._aliases + currency aliases for the database.
  static const Map<String, String> _searchAliasMap = {
    'metre': 'Meter',
    'metres': 'Meter',
    'meters': 'Meter',
    'm': 'Meter',
    'km': 'Kilometer',
    'kilometre': 'Kilometer',
    'kilometres': 'Kilometer',
    'kilometers': 'Kilometer',
    'cm': 'Centimeter',
    'centimetre': 'Centimeter',
    'centimetres': 'Centimeter',
    'mm': 'Millimeter',
    'millimetre': 'Millimeter',
    'millimetres': 'Millimeter',
    'nm': 'Nanometer',
    'μm': 'Micrometer',
    'ft': 'Foot',
    'feet': 'Foot',
    'in': 'Inch',
    'inches': 'Inch',
    'mi': 'Mile',
    'miles': 'Mile',
    'yd': 'Yard',
    'yards': 'Yard',
    'nmi': 'Nautical Mile',
    'kg': 'Kilogram',
    'kilos': 'Kilogram',
    'kilogramme': 'Kilogram',
    'g': 'Gram',
    'grams': 'Gram',
    'mg': 'Milligram',
    'lb': 'Pound',
    'lbs': 'Pound',
    'pound': 'Pound',
    'oz': 'Ounce',
    'ounces': 'Ounce',
    'stone': 'Stone',
    'st': 'Stone',
    'l': 'Liter',
    'litre': 'Liter',
    'litres': 'Liter',
    'liters': 'Liter',
    'ml': 'Milliliter',
    'millilitre': 'Milliliter',
    'gal': 'Gallon (US)',
    'gallon': 'Gallon (US)',
    'celsius': 'Celsius',
    'centigrade': 'Celsius',
    'fahrenheit': 'Fahrenheit',
    'kelvin': 'Kelvin',
    'temp': 'Temperature',
    'kph': 'Kilometers per Hour',
    'kmh': 'Kilometers per Hour',
    'mph': 'Miles per Hour',
    'knots': 'Knot',
    'byte': 'Byte',
    'bytes': 'Byte',
    'kb': 'Kilobyte',
    'mb': 'Megabyte',
    'gb': 'Gigabyte',
    'tb': 'Terabyte',
    'pb': 'Petabyte',
    's': 'Second',
    'sec': 'Second',
    'secs': 'Second',
    'seconds': 'Second',
    'min': 'Minute',
    'mins': 'Minute',
    'hr': 'Hour',
    'hrs': 'Hour',
    'hours': 'Hour',
    'day': 'Day',
    'days': 'Day',
    'week': 'Week',
    'weeks': 'Week',
    'dollar': 'US Dollar',
    'dollars': 'US Dollar',
    'euro': 'Euro',
    'euros': 'Euro',
    'pound sterling': 'British Pound',
    'yen': 'Japanese Yen',
    'rupee': 'Pakistani Rupee',
    'pkr': 'Pakistani Rupee',
    'inr': 'Indian Rupee',
    'deg': 'Degree',
    'degrees': 'Degree',
    'rad': 'Radian',
    'radians': 'Radian',
    'pascal': 'Pascal',
    'pa': 'Pascal',
    'kpa': 'Kilopascal',
    'bar': 'Bar',
    'psi': 'PSI',
    'atm': 'Atmosphere',
    'j': 'Joule',
    'joules': 'Joule',
    'kj': 'Kilojoule',
    'kwh': 'Kilowatt-hour',
    'cal': 'Calorie',
    'calories': 'Calorie',
    'w': 'Watt',
    'watts': 'Watt',
    'kw': 'Kilowatt',
    'mw': 'Megawatt',
    'hp': 'Horsepower',
    'n': 'Newton',
    'newtons': 'Newton',
    'hz': 'Hertz',
    'khz': 'Kilohertz',
    'mhz': 'Megahertz',
    'ghz': 'Gigahertz',
    'kilowatts': 'Kilowatt',
    'megawatts': 'Megawatt',
    'gw': 'Gigawatt',
    'gigawatts': 'Gigawatt',
    'horsepower': 'Horsepower',
    'kilojoules': 'Kilojoule',
    'mj': 'Megajoule',
    'megajoules': 'Megajoule',
    'kcal': 'Kilocalorie',
    'kilocalories': 'Kilocalorie',
    'btu': 'BTU',
    'btus': 'BTU',
    'wh': 'Watt-hour',
    'mwh': 'Megawatt-hour',
    'ev': 'Electronvolt',
    'hertz': 'Hertz',
    'v': 'Volt',
    'volts': 'Volt',
    'mv': 'Millivolt',
    'kv': 'Kilovolt',
    'a': 'Ampere',
    'amps': 'Ampere',
    'ampere': 'Ampere',
    'ma': 'Milliampere',
    'ka': 'Kiloampere',
    'ohm': 'Ohm',
    'ohms': 'Ohm',
    'kohm': 'Kilohm',
    'mohm': 'Megohm',
    'pf': 'Picofarad',
    'nf': 'Nanofarad',
    'uf': 'Microfarad',
    'farad': 'Farad',
    'henry': 'Henry',
    'mh': 'Millihenry',
    'uh': 'Microhenry',
    'coulomb': 'Coulomb',
    'coulombs': 'Coulomb',
    'mah': 'Milliampere-hour',
    'ah': 'Ampere-hour',
    'siemens': 'Siemens',
    'lx': 'Lux',
    'lux': 'Lux',
    'lm': 'Lumen',
    'lumens': 'Lumen',
    'cd': 'Candela',
    'candela': 'Candela',
    'nit': 'Nit',
    'nits': 'Nit',
    'fl': 'Foot-lambert',
    'klx': 'Kilolux',
    'fc': 'Foot-candle',
    'atmospheres': 'Atmosphere',
    'torr': 'Torr',
    'mbar': 'Millibar',
    'millibar': 'Millibar',
    'mpa': 'Megapascal',
    'gpa': 'Gigapascal',
    'newton': 'Newton',
    'kn': 'Kilonewton',
    'lbf': 'Pound-force',
    'dyn': 'Dyne',
    'dyne': 'Dyne',
    'nm_torque': 'Newton-meter',
    'ft_lb': 'Foot-pound',
    'rpm': 'Revolution per Minute',
    'rps': 'Revolution per Second',
    'rad/s': 'Radian per Second',
    'deg/s': 'Degree per Second',
    'm/s': 'Meter per Second',
    'm/s2': 'Meter per Second Squared',
    'ft/s2': 'Foot per Second Squared',
    'g_accel': 'Standard Gravity',
    'au': 'Astronomical Unit',
    'ly': 'Light-year',
    'lightyears': 'Light-year',
    'pc': 'Parsec',
    'parsecs': 'Parsec',
    'kpc': 'Kiloparsec',
    'mpc': 'Megaparsec',
    'bpm': 'Beats per Minute',
    'bps': 'Beats per Second',
    'mg/dl': 'Milligrams per Deciliter',
    'mmol/l': 'Millimoles per Liter',
    'mmhg': 'Millimeters of Mercury',
    'bmi': 'Body Mass Index',
    'db': 'Decibel',
    'decibel': 'Decibel',
    'decibels': 'Decibel',
    'ppm': 'Parts per Million',
    'bq': 'Becquerel',
    'becquerel': 'Becquerel',
    'ci': 'Curie',
    'curie': 'Curie',
    'mci': 'Millicurie',
    'gy': 'Gray',
    'gray': 'Gray',
    'sv': 'Sievert',
    'sievert': 'Sievert',
    'msv': 'Millisievert',
    'usv': 'Microsievert',
    'rem': 'Rem',
    'roentgen': 'Roentgen',
    'mroentgen': 'Milliroentgen',
    't': 'Tesla',
    'tesla': 'Tesla',
    'mt': 'Millitesla',
    'ut': 'Microtesla',
    'gauss': 'Gauss',
    'wb': 'Weber',
    'weber': 'Weber',
    'mwb': 'Milliweber',
    'maxwell': 'Maxwell',
    'mol': 'Mole',
    'moles': 'Mole',
    'mol/l': 'Mole per Liter',
    'g/l': 'Gram per Liter',
    'w/m-k': 'W/(m·K)',
    'c/w': '°C/W',
    'fps': 'Feet per Second',
    'mpg': 'Miles per Gallon (US)',
    'l/100km': 'Liters per 100 Kilometers',
    'cgs': 'Centimeter-Gram-Second',
    'mks': 'Meter-Kilogram-Second',
    'si': 'International System of Units',
    'dwt': 'Pennyweight',
    'sq_m': 'Square Meter',
    'sq_ft': 'Square Foot',
    'sq_mi': 'Square Mile',
    'cu_m': 'Cubic Meter',
    'cu_ft': 'Cubic Foot',
  };

  /// Seeds the [collections] table from [predefinedCollections].
  Future<void> _seedCollections(Transaction txn) async {
    var sortOrder = 0;
    for (final col in predefinedCollections) {
      await txn.insert(
        'collections',
        {
          'id': col.id,
          'name': col.name,
          'emoji': col.emoji,
          'description': col.description,
          'display_order': sortOrder++,
          'is_featured': 0,
          'is_hidden': 0,
          'search_weight': 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${predefinedCollections.length} collections');
  }

  /// Seeds [collection_items] from [predefinedCollections].
  Future<void> _seedCollectionItems(Transaction txn) async {
    var count = 0;
    for (final col in predefinedCollections) {
      var sortOrder = 0;
      for (final category in col.categories) {
        await txn.insert(
          'collection_items',
          {
            'collection_id': col.id,
            'category_id': category.name,
            'display_order': sortOrder++,
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        count++;
      }
    }
    debugPrint('[DatabaseService]   ↳ $count collection items');
  }

  /// Seeds the [currencies] table from [allIsoCurrencies].
  Future<void> _seedCurrencies(Transaction txn) async {
    var pinOrder = 0;
    for (final entry in allIsoCurrencies) {
      final isPinned = pinnedCurrencyCodes.contains(entry.code);
      await txn.insert(
        'currencies',
        {
          'iso_code': entry.code,
          'name': entry.name,
          'symbol': entry.symbol,
          'flag': entry.flag,
          'country': entry.country,
          'decimal_digits': entry.decimalDigits,
          'fallback_rate_to_usd': entry.fallbackRateToUsd,
          'is_pinned': isPinned ? 1 : 0,
          'pin_order': isPinned ? pinOrder++ : null,
          'display_order': 0,
          'is_featured': isPinned ? 1 : 0,
          'search_weight': isPinned ? 200 : 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${allIsoCurrencies.length} currencies');
  }

  /// Seeds [educational_facts] from [didYouKnowFacts].
  Future<void> _seedEducationalFacts(Transaction txn) async {
    var sortOrder = 0;
    for (final fact in didYouKnowFacts) {
      await txn.insert(
        'educational_facts',
        {
          'emoji': fact.emoji,
          'fact': fact.fact,
          'category_id': null,
          'display_order': sortOrder++,
          'is_featured': 0,
          'is_hidden': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      sortOrder++;
    }
    debugPrint('[DatabaseService]   ↳ ${didYouKnowFacts.length} educational facts');
  }

  /// Seeds [unit_information] from `assets/data/unit_information.json`.
  Future<void> _seedUnitInformation(Transaction txn) async {
    try {
      String? jsonStr;
      try {
        jsonStr = await rootBundle.loadString('assets/data/unit_information.json');
      } catch (_) {
        final file = File('assets/data/unit_information.json');
        if (await file.exists()) {
          jsonStr = await file.readAsString();
        }
      }

      if (jsonStr == null || jsonStr.isEmpty) return;

      final decoded = jsonDecode(jsonStr) as Map<String, dynamic>;
      final unitRows = await txn.query('units', columns: ['id', 'name', 'symbol']);
      final nameToUnit = <String, Map<String, dynamic>>{};
      for (final r in unitRows) {
        nameToUnit[(r['name'] as String).toLowerCase()] = r;
      }

      var count = 0;
      for (final entry in decoded.entries) {
        final key = entry.key.toLowerCase().replaceAll('_', ' ');
        final unitMap = nameToUnit[key] ?? nameToUnit[entry.key.toLowerCase()];
        if (unitMap != null) {
          final unitId = unitMap['id'] as int;
          final symbol = unitMap['symbol'] as String;
          final val = entry.value as Map<String, dynamic>;
          final definition = val['definition'] as String? ?? '';
          final history = val['history'] as String? ?? '';
          final usedFor = val['used_for'] as String? ?? '';
          final examplesList = (val['examples'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              [];

          await txn.insert(
            'unit_information',
            {
              'unit_id': unitId,
              'symbol': val['symbol'] as String? ?? symbol,
              'definition': definition,
              'history': history,
              'used_for': usedFor,
              'examples': jsonEncode(examplesList),
            },
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          count++;
        }
      }
      debugPrint('[DatabaseService]   ↳ $count unit information records');
    } catch (e) {
      debugPrint('[DatabaseService] Error seeding unit_information: $e');
    }
  }



  /// Closes the database. Should only be called when the app is disposing.

  /// Seeds [tags] and [content_tags] for cross-cutting domain taxonomy (Phase F1).
  Future<void> _seedTagsAndTaxonomy(Transaction txn) async {
    final domainTags = [
      'metric',
      'imperial',
      'si',
      'cgs',
      'everyday',
      'science',
      'engineering',
      'medical',
      'electrical',
      'optics',
      'thermodynamics',
      'astronomy',
      'digital',
      'acoustics',
      'fluid_mechanics',
      'automotive',
    ];

    final tagMap = <String, int>{};
    for (final tagName in domainTags) {
      await txn.insert(
        'tags',
        {'name': tagName},
        conflictAlgorithm: ConflictAlgorithm.ignore,
      );
      final rows = await txn.query('tags', where: 'name = ?', whereArgs: [tagName], columns: ['id']);
      if (rows.isNotEmpty) {
        tagMap[tagName] = rows.first['id'] as int;
      }
    }

    // Category taxonomy associations
    final categoryTaxonomy = <String, List<String>>{
      'length': ['metric', 'imperial', 'si', 'everyday'],
      'weight': ['metric', 'imperial', 'si', 'everyday'],
      'temperature': ['si', 'everyday', 'thermodynamics'],
      'area': ['metric', 'imperial', 'si', 'everyday'],
      'volume': ['metric', 'imperial', 'si', 'everyday'],
      'speed': ['everyday', 'automotive', 'si'],
      'data': ['digital', 'engineering'],
      'time': ['everyday', 'science', 'si'],
      'voltage': ['electrical', 'engineering', 'si'],
      'current': ['electrical', 'engineering', 'si'],
      'resistance': ['electrical', 'engineering', 'si'],
      'capacitance': ['electrical', 'engineering', 'si'],
      'inductance': ['electrical', 'engineering', 'si'],
      'power': ['electrical', 'engineering', 'automotive', 'si'],
      'energy': ['science', 'thermodynamics', 'si'],
      'pressure': ['engineering', 'fluid_mechanics', 'si'],
      'illuminance': ['optics', 'science', 'si'],
      'luminousFlux': ['optics', 'science', 'si'],
      'bloodPressure': ['medical', 'everyday'],
      'bloodSugar': ['medical', 'everyday'],
      'heartRate': ['medical', 'everyday'],
      'bmi': ['medical', 'everyday'],
      'astronomicalLength': ['astronomy', 'science'],
      'radioactivity': ['science', 'medical'],
      'radiationDose': ['science', 'medical'],
      'soundLevel': ['acoustics', 'engineering'],
      'flowRate': ['fluid_mechanics', 'engineering'],
      'density': ['science', 'fluid_mechanics'],
      'torque': ['engineering', 'automotive'],
      'fuelEconomy': ['automotive', 'everyday'],
    };

    var count = 0;
    for (final entry in categoryTaxonomy.entries) {
      final catId = entry.key;
      for (final tagName in entry.value) {
        final tagId = tagMap[tagName];
        if (tagId != null) {
          await txn.insert(
            'content_tags',
            {
              'tag_id': tagId,
              'source_type': 'category',
              'source_id': catId,
            },
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          count++;
        }
      }
    }
    debugPrint('[DatabaseService]   ↳ ${tagMap.length} tags and $count content_tags seeded');
  }

  /// Seeds [related_content] graph edges between categories (Phase G1).
  Future<void> _seedRelatedContentNetwork(Transaction txn) async {
    final relationships = <(String, String, String)>[
      ('length', 'area', 'child'),
      ('length', 'volume', 'child'),
      ('length', 'speed', 'related'),
      ('weight', 'density', 'related'),
      ('weight', 'force', 'related'),
      ('voltage', 'current', 'sibling'),
      ('voltage', 'resistance', 'sibling'),
      ('voltage', 'power', 'sibling'),
      ('current', 'conductance', 'sibling'),
      ('temperature', 'specificHeat', 'related'),
      ('temperature', 'thermalConductivity', 'related'),
      ('temperature', 'thermalResistance', 'related'),
      ('illuminance', 'luminousFlux', 'sibling'),
      ('illuminance', 'luminousIntensity', 'sibling'),
      ('illuminance', 'luminance', 'sibling'),
      ('flowRate', 'massFlowRate', 'sibling'),
      ('flowRate', 'kinematicViscosity', 'related'),
      ('kinematicViscosity', 'dynamicViscosity', 'sibling'),
      ('torque', 'power', 'related'),
      ('speed', 'fuelEconomy', 'related'),
      ('bloodPressure', 'heartRate', 'sibling'),
      ('bloodSugar', 'bmi', 'sibling'),
      ('radioactivity', 'radiationDose', 'sibling'),
      ('radiationDose', 'radiationExposure', 'sibling'),
      ('frequency', 'soundLevel', 'related'),
      ('frequency', 'wavenumber', 'related'),
    ];

    var count = 0;
    for (var i = 0; i < relationships.length; i++) {
      final (src, tgt, relType) = relationships[i];
      await txn.insert(
        'related_content',
        {
          'source_type': 'category',
          'source_id': src,
          'target_type': 'category',
          'target_id': tgt,
          'relationship_type': relType,
          'display_order': i,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      count++;
    }
    debugPrint('[DatabaseService]   ↳ $count related_content edges seeded');
  }


  Future<void> close() async {
    await _db?.close();
    _db = null;
    _initialized = false;
    debugPrint('[DatabaseService] Closed');
  }

  /// Deletes the database file. For development/testing only.
  ///
  /// Call [initialize] again to recreate and reseed.
  @visibleForTesting
  Future<void> deleteDatabase() async {
    await close();
    final dbPath = await _resolveDbPath();
    final file = File(dbPath);
    if (await file.exists()) {
      await file.delete();
      debugPrint('[DatabaseService] Database deleted: $dbPath');
    }
  }
}
