/// Singleton SQLite database manager for MS Unit Converter.
///
/// Responsibilities:
/// - Open the SQLite database (creating schema on first launch via [MigrationService]).
/// - Check [_contentVersion] against the stored version; reseed from Dart data
///   if the content has changed (new app release with updated data).
/// - Expose a single [Database] instance to all repositories via [database].
///
/// ## Phase 1 Architecture
/// The database is seeded **at runtime** from existing Dart data structures
/// on first launch. This avoids any build-tool or binary-asset dependency.
///
/// ## Phase 2 Architecture (future)
/// The database will be shipped as a pre-built binary asset
/// (`assets/database/stem_data.db`) generated by `tools/build_database.dart`
/// from JSON content files. `DatabaseService` will copy the asset to the
/// documents directory and open it from there instead of seeding at runtime.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

import '../core/constants.dart';
import 'migration_service.dart';
import '../data/collections_data.dart';
import '../data/converter_config.dart';
import '../data/currencies_data.dart';
import '../data/did_you_know.dart';
import '../data/units_data.dart';

/// Current content version — matches the app release that last changed reference data.
/// Increment this when any reference data changes (units, currencies, facts, etc.)
/// to trigger an automatic reseed on the next launch.
const String _contentVersion = '2.4.0+physics1';

/// SQLite database filename stored in the app documents directory.
const String _dbFileName = DatabaseConstants.databaseFileName;

/// Sole owner of SQLite database lifecycle.
///
/// ## ARCHITECTURE GUARDRAILS
/// Responsibilities:
/// - Copy pre-populated asset database on first launch
/// - Open and manage database connection
/// - Run schema migrations via [MigrationService]
/// - Handle content version management
///
/// **STRICT RULE**: Never implement unit conversions, business logic, or UI state here.
class DatabaseService {
  DatabaseService._();

  /// The singleton instance.
  static final DatabaseService instance = DatabaseService._();

  Database? _db;
  bool _initialized = false;

  /// Returns whether the database has been initialized and is open.
  bool get isInitialized => _initialized && _db != null && _db!.isOpen;

  /// Returns the open [Database] instance.
  ///
  /// Throws a [StateError] if [initialize] has not been called first.
  Database get database {
    if (!isInitialized) {
      throw StateError(
        'DatabaseService not initialized. '
        'Call DatabaseService.instance.initialize() before accessing the database.',
      );
    }
    return _db!;
  }

  /// Initializes the database: opens it, runs migrations, and seeds data if needed.
  ///
  /// Safe to call multiple times — subsequent calls are no-ops.
  /// First checks if the pre-populated asset database exists and copies it to
  /// the app documents directory if no database exists yet.
  Future<void> initialize() async {
    if (_initialized && _db != null && _db!.isOpen) return;

    final stopwatch = Stopwatch()..start();

    try {
      final dbPath = await _resolveDbPath();
      final dbFile = File(dbPath);

      if (!await dbFile.exists()) {
        await _copyPrePopulatedDatabase(dbPath);
      }

      debugPrint('[DatabaseService] Opening database at: $dbPath');

      _db = await openDatabase(
        dbPath,
        version: MigrationService.currentSchemaVersion,
        onCreate: (db, version) async {
          debugPrint('[DatabaseService] Creating schema (version $version)');
          await MigrationService.createSchema(db);
          await _seedAllData(db);
          await _writeVersions(db);
        },
        onUpgrade: (db, oldVersion, newVersion) async {
          debugPrint(
            '[DatabaseService] Upgrading schema: $oldVersion → $newVersion',
          );
          await MigrationService.upgrade(db, oldVersion, newVersion);
          // After a schema upgrade, check if content also needs refreshing.
          await _reseedIfContentChanged(db);
        },
        onOpen: (db) async {
          debugPrint('[DatabaseService] Database opened — checking content version');
          await _reseedIfContentChanged(db);
        },
      );

      _initialized = true;
      stopwatch.stop();

      if (kDebugMode) {
        final sizeKb = await dbFile.exists()
            ? (await dbFile.length() / 1024).toStringAsFixed(2)
            : '0.00';
        debugPrint(
          '[DatabaseService] Initialized in ${stopwatch.elapsedMilliseconds}ms — File size: $sizeKb KB',
        );
      }
    } catch (e, st) {
      stopwatch.stop();
      debugPrint('[DatabaseService] Initialization error: $e\n$st');
      rethrow;
    }
  }

  /// Copies the pre-populated SQLite asset database from [rootBundle] to [targetPath].
  ///
  /// Returns `true` if successfully copied, `false` otherwise (e.g. asset missing in tests).
  Future<bool> _copyPrePopulatedDatabase(String targetPath) async {
    try {
      debugPrint('[DatabaseService] Copying pre-populated asset database to: $targetPath');
      final file = File(targetPath);
      await file.parent.create(recursive: true);

      final data = await rootBundle.load(DatabaseConstants.databaseAssetPath);
      final bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await file.writeAsBytes(bytes, flush: true);
      debugPrint('[DatabaseService] Pre-populated database asset copied (${bytes.length} bytes)');
      return true;
    } catch (e) {
      debugPrint(
        '[DatabaseService] Asset database copy omitted/failed (falling back to dynamic seed): $e',
      );
      return false;
    }
  }

  /// Seeds all reference data and writes version metadata into [db].
  ///
  /// Exposed for [tools/build_database.dart] to generate pre-populated binaries.
  static Future<void> seedDatabase(Database db) async {
    await MigrationService.createSchema(db);
    await instance._clearReferenceData(db);
    await instance._seedAllData(db);
    await instance._writeVersions(db);
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  /// Resolves the full path to the database file in the documents directory.
  Future<String> _resolveDbPath() async {
    try {
      final dir = await getApplicationDocumentsDirectory();
      return path.join(dir.path, _dbFileName);
    } catch (_) {
      // Fallback for headless unit test runner where path_provider plugin is unmocked
      return path.join(Directory.systemTemp.path, _dbFileName);
    }
  }

  /// Checks the stored content version; reseeds all reference data if it
  /// differs from [_contentVersion].
  Future<void> _reseedIfContentChanged(Database db) async {
    final storedVersion = await _readContentVersion(db);
    if (storedVersion == _contentVersion) {
      debugPrint('[DatabaseService] Content version current ($_contentVersion) — skip reseed');
      return;
    }
    debugPrint(
      '[DatabaseService] Content version changed: '
      '${storedVersion ?? 'none'} → $_contentVersion — reseeding',
    );
    await _clearReferenceData(db);
    await _seedAllData(db);
    await _writeVersions(db);
  }

  /// Reads the stored content version from the [content_version] table.
  Future<String?> _readContentVersion(Database db) async {
    try {
      final rows = await db.query('content_version', limit: 1);
      if (rows.isEmpty) return null;
      return rows.first['version'] as String?;
    } catch (_) {
      return null;
    }
  }

  /// Clears all reference (non-user) tables before a reseed.
  Future<void> _clearReferenceData(Database db) async {
    await db.transaction((txn) async {
      for (final table in _referenceTablesToClear) {
        await txn.delete(table);
      }
    });
  }

  /// All reference tables that are cleared and reseeded on content version change.
  static const List<String> _referenceTablesToClear = [
    'related_content',
    'formulas',
    'formula_categories',
    'subjects',
    'educational_facts',
    'collection_items',
    'collections',
    'search_aliases',
    'unit_information',
    'units',
    'categories',
    'currencies',
    'content_version',
    'schema_version',
  ];

  /// Seeds all reference data into the database in a single transaction.
  Future<void> _seedAllData(Database db) async {
    debugPrint('[DatabaseService] Seeding reference data…');
    final stopwatch = Stopwatch()..start();

    await db.transaction((txn) async {
      await _seedCategories(txn);
      await _seedUnits(txn);
      await _seedSearchAliases(txn);
      await _seedCollections(txn);
      await _seedCollectionItems(txn);
      await _seedCurrencies(txn);
      await _seedEducationalFacts(txn);
      await _seedUnitInformation(txn);
      await _seedAcademyContent(txn);
    });

    stopwatch.stop();
    debugPrint('[DatabaseService] Seeding complete in ${stopwatch.elapsedMilliseconds}ms');
  }

  /// Writes the current schema and content versions to the database.
  Future<void> _writeVersions(Database db) async {
    final now = DateTime.now().toIso8601String();

    await db.transaction((txn) async {
      await txn.insert('schema_version', {
        'version': MigrationService.currentSchemaVersion,
        'applied_at': now,
        'description': 'Initial schema — MS Unit Converter v2.3.0',
      }, conflictAlgorithm: ConflictAlgorithm.replace);

      await txn.insert('content_version', {
        'id': 1,
        'version': _contentVersion,
        'generated_at': now,
        'source_hash': _contentHash,
      }, conflictAlgorithm: ConflictAlgorithm.replace);
    });
  }

  /// A simple hash of the content version string — used as a lightweight
  /// fingerprint. Replaced by a real file hash in Phase 2 (JSON source).
  String get _contentHash {
    var hash = 0;
    for (final rune in _contentVersion.runes) {
      hash = (hash * 31 + rune) & 0x7FFFFFFF;
    }
    return hash.toRadixString(16).padLeft(8, '0');
  }

  // ─── Seeders ───────────────────────────────────────────────────────────────

  /// Seeds the [categories] table from [UnitCategory] enum + [converterRegistry].
  Future<void> _seedCategories(Transaction txn) async {
    var sortOrder = 0;
    for (final category in UnitCategory.values) {
      final config = converterRegistry[category];
      await txn.insert(
        'categories',
        {
          'id': category.name,
          'display_name': category.displayName,
          'description': category.description,
          'group_name': config?.group ?? 'Other',
          'emoji': category.icon,
          'display_order': sortOrder++,
          'is_featured': _featuredCategories.contains(category) ? 1 : 0,
          'is_hidden': 0,
          'search_weight': 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${UnitCategory.values.length} categories');
  }

  /// Categories shown as "popular" or pinned on the home screen.
  static const Set<UnitCategory> _featuredCategories = {
    UnitCategory.length,
    UnitCategory.weight,
    UnitCategory.temperature,
    UnitCategory.area,
    UnitCategory.volume,
    UnitCategory.speed,
    UnitCategory.data,
    UnitCategory.time,
    UnitCategory.energy,
    UnitCategory.pressure,
  };

  /// Seeds the [units] table from [unitsData].
  Future<void> _seedUnits(Transaction txn) async {
    var totalUnits = 0;
    for (final entry in unitsData.entries) {
      var sortOrder = 0;
      for (final unit in entry.value) {
        await txn.insert(
          'units',
          {
            'category_id': entry.key.name,
            'name': unit.name,
            'symbol': unit.symbol,
            'to_base': unit.toBase,
            'is_special_case': unit.isSpecialCase ? 1 : 0,
            'group_name': unit.group,
            'display_order': sortOrder++,
            'is_featured': 0,
            'is_hidden': 0,
            'search_weight': 100,
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        totalUnits++;
      }
    }
    debugPrint('[DatabaseService]   ↳ $totalUnits units');
  }

  /// Seeds [search_aliases] from [SearchHelper._aliases] and currency aliases.
  Future<void> _seedSearchAliases(Transaction txn) async {
    var count = 0;
    for (final entry in _searchAliasMap.entries) {
      await txn.insert(
        'search_aliases',
        {
          'keyword': entry.key,
          'canonical': entry.value,
          'unit_id': null,
          'category_id': null,
          'priority': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      count++;
    }
    debugPrint('[DatabaseService]   ↳ $count search aliases');
  }

  /// Mirrors SearchHelper._aliases + currency aliases for the database.
  static const Map<String, String> _searchAliasMap = {
    // Length
    'metre': 'Meter',
    'metres': 'Meter',
    'meters': 'Meter',
    'm': 'Meter',
    'km': 'Kilometer',
    'kilometre': 'Kilometer',
    'kilometres': 'Kilometer',
    'kilometers': 'Kilometer',
    'cm': 'Centimeter',
    'centimetre': 'Centimeter',
    'centimetres': 'Centimeter',
    'mm': 'Millimeter',
    'millimetre': 'Millimeter',
    'millimetres': 'Millimeter',
    'nm': 'Nanometer',
    'μm': 'Micrometer',
    'ft': 'Foot',
    'feet': 'Foot',
    'in': 'Inch',
    'inches': 'Inch',
    'mi': 'Mile',
    'miles': 'Mile',
    'yd': 'Yard',
    'yards': 'Yard',
    'nmi': 'Nautical Mile',
    // Weight
    'kg': 'Kilogram',
    'kilos': 'Kilogram',
    'kilogramme': 'Kilogram',
    'g': 'Gram',
    'grams': 'Gram',
    'mg': 'Milligram',
    'lb': 'Pound',
    'lbs': 'Pound',
    'pound': 'Pound',
    'oz': 'Ounce',
    'ounces': 'Ounce',
    'stone': 'Stone',
    'st': 'Stone',
    // Volume
    'l': 'Liter',
    'litre': 'Liter',
    'litres': 'Liter',
    'liters': 'Liter',
    'ml': 'Milliliter',
    'millilitre': 'Milliliter',
    'gal': 'Gallon (US)',
    'gallon': 'Gallon (US)',
    // Temperature
    'celsius': 'Celsius',
    'centigrade': 'Celsius',
    'fahrenheit': 'Fahrenheit',
    'kelvin': 'Kelvin',
    'temp': 'Temperature',
    // Speed
    'kph': 'Kilometers per Hour',
    'kmh': 'Kilometers per Hour',
    'mph': 'Miles per Hour',
    'knots': 'Knot',
    // Data
    'byte': 'Byte',
    'bytes': 'Byte',
    'kb': 'Kilobyte',
    'mb': 'Megabyte',
    'gb': 'Gigabyte',
    'tb': 'Terabyte',
    'pb': 'Petabyte',
    // Time
    's': 'Second',
    'sec': 'Second',
    'secs': 'Second',
    'seconds': 'Second',
    'min': 'Minute',
    'mins': 'Minute',
    'hr': 'Hour',
    'hrs': 'Hour',
    'hours': 'Hour',
    'day': 'Day',
    'days': 'Day',
    'week': 'Week',
    'weeks': 'Week',
    // Currency
    'dollar': 'US Dollar',
    'dollars': 'US Dollar',
    'euro': 'Euro',
    'euros': 'Euro',
    'pound sterling': 'British Pound',
    'yen': 'Japanese Yen',
    'rupee': 'Pakistani Rupee',
    'pkr': 'Pakistani Rupee',
    'inr': 'Indian Rupee',
    // Angle
    'deg': 'Degree',
    'degrees': 'Degree',
    'rad': 'Radian',
    'radians': 'Radian',
    // Pressure
    'pascal': 'Pascal',
    'pa': 'Pascal',
    'kpa': 'Kilopascal',
    'bar': 'Bar',
    'psi': 'PSI',
    'atm': 'Atmosphere',
    // Energy
    'j': 'Joule',
    'joules': 'Joule',
    'kj': 'Kilojoule',
    'kwh': 'Kilowatt-hour',
    'cal': 'Calorie',
    'calories': 'Calorie',
    // Power
    'w': 'Watt',
    'watts': 'Watt',
    'kw': 'Kilowatt',
    'mw': 'Megawatt',
    'hp': 'Horsepower',
    // Force
    'n': 'Newton',
    'newtons': 'Newton',
    // Frequency
    'hz': 'Hertz',
    'khz': 'Kilohertz',
    'mhz': 'Megahertz',
    'ghz': 'Gigahertz',
  };

  /// Seeds the [collections] table from [predefinedCollections].
  Future<void> _seedCollections(Transaction txn) async {
    var sortOrder = 0;
    for (final col in predefinedCollections) {
      await txn.insert(
        'collections',
        {
          'id': col.id,
          'name': col.name,
          'emoji': col.emoji,
          'description': col.description,
          'display_order': sortOrder++,
          'is_featured': 0,
          'is_hidden': 0,
          'search_weight': 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${predefinedCollections.length} collections');
  }

  /// Seeds [collection_items] from [predefinedCollections].
  Future<void> _seedCollectionItems(Transaction txn) async {
    var count = 0;
    for (final col in predefinedCollections) {
      var sortOrder = 0;
      for (final category in col.categories) {
        await txn.insert(
          'collection_items',
          {
            'collection_id': col.id,
            'category_id': category.name,
            'display_order': sortOrder++,
          },
          conflictAlgorithm: ConflictAlgorithm.replace,
        );
        count++;
      }
    }
    debugPrint('[DatabaseService]   ↳ $count collection items');
  }

  /// Seeds the [currencies] table from [allIsoCurrencies].
  Future<void> _seedCurrencies(Transaction txn) async {
    var pinOrder = 0;
    for (final entry in allIsoCurrencies) {
      final isPinned = pinnedCurrencyCodes.contains(entry.code);
      await txn.insert(
        'currencies',
        {
          'iso_code': entry.code,
          'name': entry.name,
          'symbol': entry.symbol,
          'flag': entry.flag,
          'country': entry.country,
          'decimal_digits': entry.decimalDigits,
          'fallback_rate_to_usd': entry.fallbackRateToUsd,
          'is_pinned': isPinned ? 1 : 0,
          'pin_order': isPinned ? pinOrder++ : null,
          'display_order': 0,
          'is_featured': isPinned ? 1 : 0,
          'search_weight': isPinned ? 200 : 100,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
    }
    debugPrint('[DatabaseService]   ↳ ${allIsoCurrencies.length} currencies');
  }

  /// Seeds [educational_facts] from [didYouKnowFacts].
  Future<void> _seedEducationalFacts(Transaction txn) async {
    var sortOrder = 0;
    for (final fact in didYouKnowFacts) {
      await txn.insert(
        'educational_facts',
        {
          'emoji': fact.emoji,
          'fact': fact.fact,
          'category_id': null,
          'display_order': sortOrder++,
          'is_featured': 0,
          'is_hidden': 0,
        },
        conflictAlgorithm: ConflictAlgorithm.replace,
      );
      sortOrder++;
    }
    debugPrint('[DatabaseService]   ↳ ${didYouKnowFacts.length} educational facts');
  }

  /// Seeds [unit_information] from `assets/data/unit_information.json`.
  Future<void> _seedUnitInformation(Transaction txn) async {
    try {
      String? jsonStr;
      try {
        jsonStr = await rootBundle.loadString('assets/data/unit_information.json');
      } catch (_) {
        final file = File('assets/data/unit_information.json');
        if (await file.exists()) {
          jsonStr = await file.readAsString();
        }
      }

      if (jsonStr == null || jsonStr.isEmpty) return;

      final decoded = jsonDecode(jsonStr) as Map<String, dynamic>;
      final unitRows = await txn.query('units', columns: ['id', 'name', 'symbol']);
      final nameToUnit = <String, Map<String, dynamic>>{};
      for (final r in unitRows) {
        nameToUnit[(r['name'] as String).toLowerCase()] = r;
      }

      var count = 0;
      for (final entry in decoded.entries) {
        final key = entry.key.toLowerCase().replaceAll('_', ' ');
        final unitMap = nameToUnit[key] ?? nameToUnit[entry.key.toLowerCase()];
        if (unitMap != null) {
          final unitId = unitMap['id'] as int;
          final symbol = unitMap['symbol'] as String;
          final val = entry.value as Map<String, dynamic>;
          final definition = val['definition'] as String? ?? '';
          final history = val['history'] as String? ?? '';
          final usedFor = val['used_for'] as String? ?? '';
          final examplesList = (val['examples'] as List<dynamic>?)
                  ?.map((e) => e.toString())
                  .toList() ??
              [];

          await txn.insert(
            'unit_information',
            {
              'unit_id': unitId,
              'symbol': val['symbol'] as String? ?? symbol,
              'definition': definition,
              'history': history,
              'used_for': usedFor,
              'examples': jsonEncode(examplesList),
            },
            conflictAlgorithm: ConflictAlgorithm.replace,
          );
          count++;
        }
      }
      debugPrint('[DatabaseService]   ↳ $count unit information records');
    } catch (e) {
      debugPrint('[DatabaseService] Error seeding unit_information: $e');
    }
  }

  /// Seeds STEM Academy subjects, categories, and formulas into [txn].
  Future<void> _seedAcademyContent(Transaction txn) async {
    // 1. Subjects
    final subjects = [
      {'id': 1, 'name': 'Mathematics', 'icon': '📐', 'display_order': 1},
      {'id': 2, 'name': 'Physics', 'icon': '⚛️', 'display_order': 2},
      {'id': 3, 'name': 'Chemistry', 'icon': '🧪', 'display_order': 3},
      {'id': 4, 'name': 'Engineering', 'icon': '⚙️', 'display_order': 4},
      {'id': 5, 'name': 'Computer Science', 'icon': '💻', 'display_order': 5},
      {'id': 6, 'name': 'Scientific Constants', 'icon': '🔬', 'display_order': 6},
    ];
    for (final s in subjects) {
      await txn.insert('subjects', s, conflictAlgorithm: ConflictAlgorithm.replace);
    }

    // 2. Categories
    final categories = [
      {'id': 'algebra', 'name': 'Algebra', 'subject_id': 1, 'description': 'Linear, quadratic, and polynomial equations.', 'display_order': 1},
      {'id': 'geometry', 'name': 'Geometry', 'subject_id': 1, 'description': '2D/3D shapes, area, volume, and perimeter.', 'display_order': 2},
      {'id': 'trigonometry', 'name': 'Trigonometry', 'subject_id': 1, 'description': 'Sine, cosine, tangent, and trigonometric identities.', 'display_order': 3},
      {'id': 'coordinate_geometry', 'name': 'Coordinate Geometry', 'subject_id': 1, 'description': 'Distance, midpoint, and lines on Cartesian plane.', 'display_order': 4},
      {'id': 'calculus', 'name': 'Calculus', 'subject_id': 1, 'description': 'Limits, derivatives, integrals, and rate of change.', 'display_order': 5},
      {'id': 'probability', 'name': 'Probability', 'subject_id': 1, 'description': 'Permutations, combinations, and likelihood.', 'display_order': 6},
      {'id': 'statistics', 'name': 'Statistics', 'subject_id': 1, 'description': 'Mean, median, mode, and standard deviation.', 'display_order': 7},
      {'id': 'matrices', 'name': 'Matrices & Determinants', 'subject_id': 1, 'description': 'Matrix arithmetic, inverses, and determinants.', 'display_order': 8},
      {'id': 'vectors', 'name': 'Vectors', 'subject_id': 1, 'description': 'Dot product, cross product, and magnitude.', 'display_order': 9},
      {'id': 'logarithms', 'name': 'Logarithms & Exponents', 'subject_id': 1, 'description': 'Log rules, natural logs, and exponential growth.', 'display_order': 10},
      {'id': 'kinematics', 'name': 'Kinematics & Motion', 'subject_id': 2, 'description': 'Motion of objects without forces.', 'display_order': 1},
      {'id': 'dynamics', 'name': 'Dynamics & Forces', 'subject_id': 2, 'description': 'Forces and laws of motion.', 'display_order': 2},
      {'id': 'work_energy', 'name': 'Work, Energy & Power', 'subject_id': 2, 'description': 'Energy transfers and rate of work.', 'display_order': 3},
      {'id': 'matter', 'name': 'Properties of Matter', 'subject_id': 2, 'description': 'Density and fluid pressure.', 'display_order': 4},
      {'id': 'thermal_physics', 'name': 'Thermal Physics', 'subject_id': 2, 'description': 'Heat and temperature.', 'display_order': 5},
      {'id': 'waves_optics', 'name': 'Waves & Optics', 'subject_id': 2, 'description': 'Waves and optics.', 'display_order': 6},
      {'id': 'electricity', 'name': 'Electricity & Circuits', 'subject_id': 2, 'description': 'Circuits and Ohm\'s Law.', 'display_order': 7},
      {'id': 'magnetism', 'name': 'Magnetism & Electromagnetism', 'subject_id': 2, 'description': 'Magnetic forces and fields.', 'display_order': 8},
    ];
    for (final c in categories) {
      await txn.insert('formula_categories', c, conflictAlgorithm: ConflictAlgorithm.replace);
    }

    // 3. Formulas
    final formulas = [
      {
        'id': 101,
        'subject_id': 1,
        'category_id': 'algebra',
        'chapter': 'Quadratic Equations',
        'title': 'Quadratic Formula',
        'expression': 'x = (-b ± √(b² - 4ac)) / (2a)',
        'description': 'Calculates the real or complex roots of any second-degree quadratic equation ax² + bx + c = 0.',
        'difficulty': '2',
        'variables': '[{"symbol":"a","name":"Quadratic Coefficient","description":"Multiplier of x² (a ≠ 0)"},{"symbol":"b","name":"Linear Coefficient","description":"Multiplier of x"},{"symbol":"c","name":"Constant Term","description":"Independent term"},{"symbol":"x","name":"Roots / Solutions","description":"Values of x where equation equals 0"}]',
        'example': '{"problem":"Find roots of 2x² - 4x - 6 = 0","steps":["Identify a = 2, b = -4, c = -6","Discriminant b² - 4ac = 16 - 4(2)(-6) = 64","x = (4 ± √64) / 4 = (4 ± 8) / 4","x₁ = 3, x₂ = -1"],"solution":"x = 3 or x = -1"}',
        'units': '3',
        'display_order': 1,
      },
      {
        'id': 102,
        'subject_id': 1,
        'category_id': 'geometry',
        'chapter': 'Right Triangles',
        'title': 'Pythagorean Theorem',
        'expression': 'a² + b² = c²',
        'description': 'Relates the side lengths of a right-angled triangle where c is the hypotenuse.',
        'difficulty': '1',
        'variables': '[{"symbol":"a","name":"Leg A","description":"First perpendicular side"},{"symbol":"b","name":"Leg B","description":"Second perpendicular side"},{"symbol":"c","name":"Hypotenuse","description":"Longest side opposite the right angle"}]',
        'example': '{"problem":"Calculate hypotenuse when a = 3 cm and b = 4 cm","steps":["a² = 9, b² = 16","c² = 9 + 16 = 25","c = √25 = 5"],"solution":"c = 5 cm"}',
        'units': '2',
        'display_order': 2,
      },
      {
        'id': 201,
        'subject_id': 2,
        'category_id': 'kinematics',
        'chapter': 'Motion in One Dimension',
        'title': 'Speed & Velocity',
        'expression': 'v = d / t',
        'description': 'Speed is the rate at which distance is covered.',
        'difficulty': '1',
        'variables': '[{"symbol":"v","name":"Speed","description":"m/s"},{"symbol":"d","name":"Distance","description":"m"},{"symbol":"t","name":"Time","description":"s"}]',
        'calculator_json': '{"version":"1.0","engine_type":"expression","expression":"d / t","inputs":[{"symbol":"d","label":"Distance","default_value":150.0},{"symbol":"t","label":"Time","default_value":10.0}],"outputs":[{"symbol":"v","label":"Speed","unit":"m/s"}]}',
        'units': '3',
        'display_order': 1,
      },
      {
        'id': 202,
        'subject_id': 2,
        'category_id': 'kinematics',
        'chapter': 'Linear Acceleration',
        'title': 'Acceleration',
        'expression': 'a = (v - u) / t',
        'description': 'Rate of change of velocity.',
        'difficulty': '1',
        'variables': '[{"symbol":"a","name":"Acceleration","description":"m/s²"},{"symbol":"v","name":"Final Velocity","description":"m/s"},{"symbol":"u","name":"Initial Velocity","description":"m/s"},{"symbol":"t","name":"Time","description":"s"}]',
        'calculator_json': '{"version":"1.0","engine_type":"expression","expression":"(v - u) / t","inputs":[{"symbol":"v","label":"Final Velocity","default_value":30.0},{"symbol":"u","label":"Initial Velocity","default_value":10.0},{"symbol":"t","label":"Time","default_value":5.0}],"outputs":[{"symbol":"a","label":"Acceleration","unit":"m/s²"}]}',
        'units': '3',
        'display_order': 2,
      },
      {
        'id': 203,
        'subject_id': 2,
        'category_id': 'dynamics',
        'chapter': 'Newton\'s Laws',
        'title': 'Newton\'s Second Law of Motion',
        'expression': 'F = m * a',
        'description': 'Acceleration is directly proportional to net force.',
        'difficulty': '1',
        'variables': '[{"symbol":"F","name":"Force","description":"N"},{"symbol":"m","name":"Mass","description":"kg"},{"symbol":"a","name":"Acceleration","description":"m/s²"}]',
        'calculator_json': '{"version":"1.0","engine_type":"expression","expression":"m * a","inputs":[{"symbol":"m","label":"Mass","default_value":5.0},{"symbol":"a","label":"Acceleration","default_value":3.0}],"outputs":[{"symbol":"F","label":"Force","unit":"N"}]}',
        'units': '3',
        'display_order': 1,
      },
    ];

    for (final f in formulas) {
      await txn.insert('formulas', f, conflictAlgorithm: ConflictAlgorithm.replace);
    }
  }

  /// Closes the database. Should only be called when the app is disposing.
  Future<void> close() async {
    await _db?.close();
    _db = null;
    _initialized = false;
    debugPrint('[DatabaseService] Closed');
  }

  /// Deletes the database file. For development/testing only.
  ///
  /// Call [initialize] again to recreate and reseed.
  @visibleForTesting
  Future<void> deleteDatabase() async {
    await close();
    final dbPath = await _resolveDbPath();
    final file = File(dbPath);
    if (await file.exists()) {
      await file.delete();
      debugPrint('[DatabaseService] Database deleted: $dbPath');
    }
  }
}
